# Midline Data - Herat & Jalalabad


## About
**The data**
This data is part of 3 distinct data collections made as part of a humanitarian program. The data was collected through surveys in 2015 *(confirm date)*: before the program started (baseline), during the program (midline) and after the program (endline). Households were selected randomly *(confirm study design methods)*

For the midline, the subject of this notebook, the data was collected in two Afghan cities: Herat & Jalalabad.

**The program**
The program aimed at supporting people that had been uprooted. It was meant to support their livelihood situation through training, such as literacy training or vocational training and self-help groups to support each other and build basic social safety nets within the community.


### Challenges
- The data has almost as many features as observations
- There are many NAs to deal with, but also typos in the questions and answers, unordered Q, etc.
- There is little context about the data, the questions, etc. 
- There's a widespread use of unknown abbreviations and long feature names 
- Finally, there are discrepancies between the features for the two cities

### Goal
The goal of this notebook is to clean the data in order to then perform exploratory data analysis, or train a model if relevant.

The overall goal is to understand if the population's conditions were improved with the help of the project, compared to before the project started. We'd like to understand what has changed and how, and what has remained the same. 


## Intro 
Loading the datasets and taking a first look at them

In [1]:
#load libraries
import numpy as np
import pandas as pd

In [2]:
#helper functions

def clean_df(df, new_col_names, na_val = -1):
    """ Perform several cleaning tasks: rename columns, transform null values, 
    change relevant columns to binary and integer, then display the result """
    df.columns = new_col_names
    
    encode_na_df(df, na_val)
    encode_binary_df(df)
    convert_float_int_df(df)
    
    display_df(df)   
    return df

def encode_binary(df,col):
    """ Transform col with 'yes'/'no', 'True'/'False' values to binary 1/0 """
    if (df[col].unique().tolist() == ['yes', 'no']) or (df[col].unique().tolist() == ['no', 'yes']) :
        df.loc[df[col]=='yes',col] =1
        df.loc[df[col]=='no',col] =0  
    if (df[col].unique().tolist() == [True, False]) or (df[col].unique().tolist() == [False, True]) :
        df.loc[df[col]==True,col] =1
        df.loc[df[col]==False,col] =0      
        
def encode_binary_df(df):
    """Check all cols in df and binary encode them if 'yes'/'no' type"""
    for col in df:
        encode_binary(df,col)        
        
        
def encode_na(df, col, na_val = -1):
    """Transform NAs in col into na_val"""
    df.loc[df[col].isna(),col] = na_val
    
def encode_na_df(df, na_val = -1):
    """Transform NAs in df into na_val"""
    for col in df:
        encode_na(df, col, na_val)    
    
def encode(df, col, old_val, new_val):
    """Update old_val in given column to new_val"""
    df.loc[df[col]==old_val,col] = new_val    
    
def convert_float_int(df,col):
    """Convert float column to int"""
    if df[col].dtypes == 'float64':
        df[col] = df[col].astype('int')  

def convert_float_int_df(df):
    """Converts floats columns in df to int"""
    for col in df:
        convert_float_int(df, col)

def display_df(df):
    """ Print the column name and unique values for each column of df"""
    for col in df:
        print(col, df[col].unique().tolist())
        
def drop_na(df, col, threshold_perc = .98):
    """ Drop given column from given df if proportion of NAs above threshold """
    if sum(df[col].isna())/len(df[col]) > threshold_perc:
        df.drop(col, axis=1, inplace = True)
        
def drop_na_df(df, threshold_perc = .98):
    """ Drop all columns above NA threshold from df """
    for col in df:
        drop_na(df, col, threshold_perc = .98)

In [3]:
#load data 
jlbd = pd.read_excel('jlbd_midterm.xlsx')
herat = pd.read_excel('herat_midterm.xlsx')
herat = herat.iloc[:-2, :] #removing last 2 rows, only NAs
#Removing firstname, lastname, id (anonimity, no use)
herat.drop(['a_basics/a01', 'a_basics/a03','a_basics/respondent_id'], axis=1, inplace = True) 
jlbd.drop(['a_basics/a01', 'a_basics/a03','a_basics/respondent_id'], axis=1, inplace = True)

### Herat
##### 1. Basics

In [4]:
df = herat
drop_na_df(df) #removing columns with more than 98% NAs

# info on the survey - we might not use it but saving it just in case
herat_info = pd.concat([df.iloc[:,0:2], df.iloc[:,-6:]], axis=1) 
herat_info

,start,end,meta/instanceID,_id,_uuid,_submission_time,_index,_parent_index
0,2017-03-19T16:04:33.121Z,2017-03-19T21:36:08.260Z,uuid:c129af20-0b82-4b1d-af3d-926ebd070a3c,7151078.0,c129af20-0b82-4b1d-af3d-926ebd070a3c,2017-03-12T11:21:46,1.0,-1.0
1,2017-03-19T16:50:46.243Z,2017-03-19T21:35:52.332Z,uuid:cb279127-5631-4fd2-aaa4-699f0aad5a63,7151082.0,cb279127-5631-4fd2-aaa4-699f0aad5a63,2017-03-12T11:21:49,2.0,-1.0
2,2017-03-19T20:17:44.817Z,2017-03-19T21:11:05.506Z,uuid:d546f6ee-daf4-490b-913f-b954ee4845d8,7151084.0,d546f6ee-daf4-490b-913f-b954ee4845d8,2017-03-12T11:21:51,3.0,-1.0
3,2017-03-19T20:41:07.042Z,2017-03-19T21:09:39.951Z,uuid:f14e1268-5fcf-4dd9-8a3c-cbe98f993a6a,7151086.0,f14e1268-5fcf-4dd9-8a3c-cbe98f993a6a,2017-03-12T11:21:52,4.0,-1.0
4,2017-03-12T09:06:41.021+04:30,2017-03-12T13:33:57.408+04:30,uuid:5089966a-66c0-40b9-a2bc-b56f4a6c5066,7151688.0,5089966a-66c0-40b9-a2bc-b56f4a6c5066,2017-03-12T11:30:10,5.0,-1.0
5,2017-03-12T09:49:23.155+04:30,2017-03-12T10:29:28.294+04:30,uuid:01dc8cd9-1dc4-446c-8849-afe1af4e6126,7151692.0,01dc8cd9-1dc4-446c-8849-afe1af4e6126,2017-03-12T11:30:12,6.0,-1.0
6,2017-03-12T11:57:41.815+04:30,2017-03-12T12:08:31.188+04:30,uuid:2d8b7632-cd6a-489a-b9b9-f8af82daa641,7151698.0,2d8b7632-cd6a-489a-b9b9-f8af82daa641,2017-03-12T11:30:16,7.0,-1.0
7,2017-03-12T13:51:05.075+04:30,2017-03-12T14:24:57.116+04:30,uuid:305d846e-67e0-496c-b189-df2b083e6efe,7151699.0,305d846e-67e0-496c-b189-df2b083e6efe,2017-03-12T11:30:19,8.0,-1.0
8,2017-03-12T14:26:30.190+04:30,2017-03-12T15:59:05.316+04:30,uuid:2ed05bc4-762f-411d-b66c-3434faeaf284,7151700.0,2ed05bc4-762f-411d-b66c-3434faeaf284,2017-03-12T11:30:20,9.0,-1.0
9,2017-03-12T09:15:22.690+04:30,2017-03-12T15:59:42.913+04:30,uuid:3d9c259e-9b87-477a-82d2-e2f854dddb93,7151787.0,3d9c259e-9b87-477a-82d2-e2f854dddb93,2017-03-12T11:32:09,10.0,-1.0
10,2017-03-12T09:48:54.413+04:30,2017-03-12T10:05:24.979+04:30,uuid:ebea3269-1494-4f87-8247-3d1156befe8a,7151789.0,ebea3269-1494-4f87-8247-3d1156befe8a,2017-03-12T11:32:12,11.0,-1.0
11,2017-03-12T10:49:41.584+04:30,2017-03-12T11:10:51.138+04:30,uuid:c39aad52-b88e-40ab-9c39-495db103db88,7151800.0,c39aad52-b88e-40ab-9c39-495db103db88,2017-03-12T11:32:29,12.0,-1.0
12,2017-03-12T13:52:19.085+04:30,2017-03-12T16:01:25.587+04:30,uuid:08f0f94c-946c-46eb-a450-962e39d99d6d,7151802.0,08f0f94c-946c-46eb-a450-962e39d99d6d,2017-03-12T11:32:31,13.0,-1.0
13,2017-03-12T14:21:21.170+04:30,2017-03-12T14:43:02.204+04:30,uuid:80dc7fe0-0a25-4e49-8cc1-366295fad27a,7151804.0,80dc7fe0-0a25-4e49-8cc1-366295fad27a,2017-03-12T11:32:33,14.0,-1.0
14,2017-03-12T10:29:06.842+04:30,2017-03-12T10:49:01.610+04:30,uuid:49dff6a7-367d-4236-8c13-70857b09637d,7151808.0,49dff6a7-367d-4236-8c13-70857b09637d,2017-03-12T11:32:42,15.0,-1.0
15,2017-03-12T09:10:31.064+04:30,2017-03-08T18:44:07.122+04:30,uuid:7057ad46-f54e-4460-a857-aa034720d216,7151862.0,7057ad46-f54e-4460-a857-aa034720d216,2017-03-12T11:34:25,16.0,-1.0
16,2017-03-12T09:47:36.353+04:30,2017-03-08T18:43:47.753+04:30,uuid:15a49206-cd36-4e7d-ac77-d469de0ddb5b,7151863.0,15a49206-cd36-4e7d-ac77-d469de0ddb5b,2017-03-12T11:34:27,17.0,-1.0
17,2017-03-12T10:05:01.554+04:30,2017-03-08T18:46:50.641+04:30,uuid:61d6dc47-7285-457b-afba-98a73f0cdb1a,7151864.0,61d6dc47-7285-457b-afba-98a73f0cdb1a,2017-03-12T11:34:28,18.0,-1.0
18,2017-03-08T16:46:31.346+04:30,2017-03-08T18:46:34.072+04:30,uuid:8c15b045-7996-4bf5-b9a0-d97d45ac45ad,7151868.0,8c15b045-7996-4bf5-b9a0-d97d45ac45ad,2017-03-12T11:34:32,19.0,-1.0
19,2017-03-08T17:11:31.785+04:30,2017-03-08T18:46:07.638+04:30,uuid:155b5ba1-e755-4cc0-bbbc-215f26e67913,7151871.0,155b5ba1-e755-4cc0-bbbc-215f26e67913,2017-03-12T11:34:34,20.0,-1.0
20,2017-03-08T17:41:56.692+04:30,2017-03-08T18:45:17.414+04:30,uuid:56bc9919-cb55-45ab-b407-ae36263992d5,7151877.0,56bc9919-cb55-45ab-b407-ae36263992d5,2017-03-12T11:34:38,21.0,-1.0
21,2017-03-12T09:05:52.384+04:30,2017-03-12T13:21:11.591+04:30,uuid:1e3de2a0-077d-4ad1-bd08-416751aac01b,7151886.0,1e3de2a0-077d-4ad1-bd08-416751aac01b,2017-03-12T11:34:55,22.0,-1.0
22,2017-03-12T09:44:50.281+04:30,2017-03-12T13:25:31.992+04:30,uuid:cf498bb8-f702-4b59-8c7d-7f8bc34ee5c7,7151887.0,cf498bb8-f702-4b59-8c7d-7f8bc34ee5c7,2017-03-12T11:34:56,23.0,-1.0
23,2017-03-12T10:10:57.165+04:30,2017-03-12T13:27:07.147+04:30,uuid:8eab88e6-f191-46c8-ad01-9a0ca1535ffc,7151888.0,8eab88e6-f191-46c8-ad01-9a0ca1535ffc,2017-03-12T11:34:57,24.0,-1.0
24,2017-03-12T10:44:38.664+04:30,2017-03-12T13:27:52.864+04:30,uuid:89de5f9e-edfb-487d-94fd-c51399b0c563,7151889.0,89de5f9e-edfb-487d-94fd-c51399b0c563,2017-03-12T11:34:58,25.0,-1.0
25,2017-03-12T14:02:10.447+04:30,2017-03-12T14:31:19.474+04:30,uuid:d5dc301d-c18a-428f-8119-1a18f25a1560,7151892.0,d5dc301d-c18a-428f-8119-1a18f25a1560,2017-03-12T11:35:01,26.0,-1.0
26,2017-03-12T14:56:11.371+04:30,2017-03-12T15:26:11.964+04:30,uuid:f1a63bba-a539-483d-a9a4-b99ac9656b3d,7151894.0,f1a63bba-a539-483d-a9a4-b99ac9656b3d,2017-03-12T11:35:05,27.0,-1.0
27,2017-03-12T04:40:39.929Z,2017-03-12T09:18:13.968Z,uuid:c779c218-a08a-4c9e-b089-fc4cd26122a2,7151922.0,c779c218-a08a-4c9e-b089-fc4cd26122a2,2017-03-12T11:35:52,28.0,-1.0
28,2017-03-12T05:11:11.695Z,2017-03-12T09:16:29.704Z,uuid:e6946b72-ce35-430a-8310-d869a4b17b42,7151926.0,e6946b72-ce35-430a-8310-d869a4b17b42,2017-03-12T11:35:54,29.0,-1.0
29,2017-03-12T05:39:45.484Z,2017-03-12T09:17:12.087Z,uuid:a65cb853-8cc1-4eba-9726-2be6e0db137d,7151930.0,a65cb853-8cc1-4eba-9726-2be6e0db137d,2017-03-12T11:35:57,30.0,-1.0
...,...,...,...,...,...,...,...,...
318,2017-03-30T13:46:59.687+04:30,2017-03-30T14:13:10.790+04:30,uuid:e1f95c33-49d8-4df5-90c8-4c3f88d7c3ff,7606374.0,e1f95c33-49d8-4df5-90c8-4c3f88d7c3ff,2017-03-30T11:18:54,319.0,-1.0
319,2017-03-30T14:13:42.829+04:30,2017-03-30T14:34:26.531+04:30,uuid:7842c3b0-bf52-4c83-baea-85c98737bf4e,7606376.0,7842c3b0-bf52-4c83-baea-85c98737bf4e,2017-03-30T11:18:59,320.0,-1.0
320,2017-03-30T14:35:12.559+04:30,2017-03-30T14:48:59.111+04:30,uuid:60d601ae-ef59-4370-b1e0-c55c3035bd39,7606378.0,60d601ae-ef59-4370-b1e0-c55c3035bd39,2017-03-30T11:19:09,321.0,-1.0
321,2017-03-29T20:14:14.549+04:30,2017-03-29T20:25:33.934+04:30,uuid:875460a3-ffd2-446b-9389-9635425b760a,7606381.0,875460a3-ffd2-446b-9389-9635425b760a,2017-03-30T11:19:18,322.0,-1.0
322,2017-03-29T20:41:50.359+04:30,2017-03-29T20:52:03.868+04:30,uuid:127dafb8-4af3-4c4b-8ab3-31ae3c546e94,7606383.0,127dafb8-4af3-4c4b-8ab3-31ae3c546e94,2017-03-30T11:19:19,323.0,-1.0
323,2017-03-29T20:53:26.105+04:30,2017-03-29T21:01:12.094+04:30,uuid:f1671ac3-61a9-4d09-aeeb-827f9ceb282c,7606385.0,f1671ac3-61a9-4d09-aeeb-827f9ceb282c,2017-03-30T11:19:21,324.0,-1.0
324,2017-03-29T21:01:19.312+04:30,2017-03-29T21:11:29.743+04:30,uuid:3d0fbdc2-cbd1-4d96-bb88-25b65c14a3f5,7606410.0,3d0fbdc2-cbd1-4d96-bb88-25b65c14a3f5,2017-03-30T11:20:17,325.0,-1.0
325,2017-03-29T21:46:25.802+04:30,2017-03-29T21:55:16.460+04:30,uuid:00b6bb14-9975-4c05-b628-471ccc84ce46,7606411.0,00b6bb14-9975-4c05-b628-471ccc84ce46,2017-03-30T11:20:19,326.0,-1.0
326,2017-03-29T22:27:51.370+04:30,2017-03-29T22:32:51.637+04:30,uuid:213f71ea-a049-4236-958d-c71235a5337a,7606441.0,213f71ea-a049-4236-958d-c71235a5337a,2017-03-30T11:20:39,327.0,-1.0
327,2017-03-30T02:25:07.179+04:30,2017-03-30T02:32:32.439+04:30,uuid:fee854c0-a806-4158-8f2f-9d0158cb3668,7606446.0,fee854c0-a806-4158-8f2f-9d0158cb3668,2017-03-30T11:20:49,328.0,-1.0
328,2017-03-30T02:32:42.274+04:30,2017-03-30T02:39:24.289+04:30,uuid:2f00f557-3852-47c4-b721-a6c57c14706a,7606448.0,2f00f557-3852-47c4-b721-a6c57c14706a,2017-03-30T11:20:51,329.0,-1.0
329,2017-04-05T15:23:03.809Z,2017-04-05T17:40:02.546Z,uuid:3bcc6324-558c-4290-84e2-fc9260c8c015,7606546.0,3bcc6324-558c-4290-84e2-fc9260c8c015,2017-03-30T11:23:24,330.0,-1.0
330,2017-04-05T15:56:15.888Z,2017-04-05T17:40:12.420Z,uuid:ea34c56d-6858-4fec-8c3d-5cb369443c2c,7606548.0,ea34c56d-6858-4fec-8c3d-5cb369443c2c,2017-03-30T11:23:30,331.0,-1.0
331,2017-04-05T21:13:25.094Z,2017-04-05T22:17:08.674Z,uuid:d857713b-d6ad-44a0-a894-6166a8cecbd2,7606550.0,d857713b-d6ad-44a0-a894-6166a8cecbd2,2017-03-30T11:23:34,332.0,-1.0
332,2017-04-06T15:13:13.734Z,2017-04-06T16:25:19.248Z,uuid:f2ccd86a-db09-448d-bc03-3af78fbce323,7606552.0,f2ccd86a-db09-448d-bc03-3af78fbce323,2017-03-30T11:23:35,333.0,-1.0
333,2017-04-06T19:59:56.593Z,2017-04-06T20:27:41.621Z,uuid:22e7187f-464d-4f07-8367-c01376939ed1,7606553.0,22e7187f-464d-4f07-8367-c01376939ed1,2017-03-30T11:23:37,334.0,-1.0
334,2017-04-06T20:48:15.778Z,2017-04-06T20:59:16.299Z,uuid:37733b42-3cf2-4b4e-b0c0-7afd4ee7caab,7606554.0,37733b42-3cf2-4b4e-b0c0-7afd4ee7caab,2017-03-30T11:23:40,335.0,-1.0
335,2017-03-30T13:44:29.074+04:30,2017-03-30T14:03:45.010+04:30,uuid:bfdc5480-e4c3-4b48-9aa9-e9cb88fb23c8,7606569.0,bfdc5480-e4c3-4b48-9aa9-e9cb88fb23c8,2017-03-30T11:24:32,336.0,-1.0
336,2017-03-30T14:04:07.681+04:30,2017-03-30T14:23:21.003+04:30,uuid:cfac5f12-f896-4329-90ba-6f9584787749,7606571.0,cfac5f12-f896-4329-90ba-6f9584787749,2017-03-30T11:24:37,337.0,-1.0
337,2017-03-30T08:54:56.095+04:30,2017-03-30T09:39:08.044+04:30,uuid:bc9ecad8-b727-4b0b-9b47-3b21046265fe,7606582.0,bc9ecad8-b727-4b0b-9b47-3b21046265fe,2017-03-30T11:24:52,338.0,-1.0
338,2017-03-30T08:48:19.273+04:30,2017-03-30T09:03:20.874+04:30,uuid:ef66b636-0178-4759-9cfa-eac2a8a72b70,7627797.0,ef66b636-0178-4759-9cfa-eac2a8a72b70,2017-03-31T09:58:00,339.0,-1.0
339,2017-03-30T13:47:55.950+04:30,2017-03-30T14:13:37.446+04:30,uuid:790faf0d-cfd5-416a-9cc8-da205f8248e2,7627802.0,790faf0d-cfd5-416a-9cc8-da205f8248e2,2017-03-31T09:58:05,340.0,-1.0
340,2017-03-30T09:23:09.320+04:30,2017-03-30T09:43:52.562+04:30,uuid:b9951755-b2d6-42a3-ac76-8f8957fc9322,7659231.0,b9951755-b2d6-42a3-ac76-8f8957fc9322,2017-04-02T04:11:08,341.0,-1.0
341,2017-03-30T10:04:54.204+04:30,2017-03-30T10:26:26.595+04:30,uuid:816e1a26-e936-4cc7-a2e5-cf12e9d03640,7659232.0,816e1a26-e936-4cc7-a2e5-cf12e9d03640,2017-04-02T04:11:09,342.0,-1.0
342,2017-03-30T14:16:45.991+04:30,2017-03-30T14:33:57.007+04:30,uuid:01d5cec6-7ecc-4028-8f79-cd1bcccd2648,7659233.0,01d5cec6-7ecc-4028-8f79-cd1bcccd2648,2017-04-02T04:11:10,343.0,-1.0
343,2017-03-30T14:34:48.246+04:30,2017-03-30T14:52:15.686+04:30,uuid:ce7c833c-1487-416f-90ae-5007315c51f3,7659234.0,ce7c833c-1487-416f-90ae-5007315c51f3,2017-04-02T04:11:12,344.0,-1.0
344,2017-03-30T15:03:01.647+04:30,2017-03-30T15:18:59.151+04:30,uuid:c5c86c49-3c0c-4c44-9572-fbbe323db90c,7659235.0,c5c86c49-3c0c-4c44-9572-fbbe323db90c,2017-04-02T04:11:14,345.0,-1.0
345,2017-03-30T15:19:19.335+04:30,2017-03-30T15:36:18.746+04:30,uuid:b5b50b52-296a-4d79-8830-a718a7375b0d,7659238.0,b5b50b52-296a-4d79-8830-a718a7375b0d,2017-04-02T04:11:32,346.0,-1.0
346,2017-04-02T09:09:49.917+04:30,2017-04-02T09:57:19.871+04:30,uuid:82582a8b-0d03-4a04-bfe7-6659b2d3be59,7664031.0,82582a8b-0d03-4a04-bfe7-6659b2d3be59,2017-04-02T12:26:08,347.0,-1.0
347,2017-04-02T09:03:54.013+04:30,2017-04-02T09:20:38.816+04:30,uuid:15df212c-3884-4950-a8f1-6f2e386e1091,7664039.0,15df212c-3884-4950-a8f1-6f2e386e1091,2017-04-02T12:27:40,348.0,-1.0

In [5]:
# Using same sections as for baseline cleaning
herat_basics = df.loc[:,'city':'a_hh']
herat_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 32 columns):
city                                                                               348 non-null object
enumh_id                                                                           348 non-null object
loc_herat                                                                          348 non-null object
a_basics/a02                                                                       348 non-null object
A05. Which activities do you participate/d in?                                     348 non-null object
a_basics/a_p/shgs                                                                  348 non-null float64
a_basics/a_p/vt                                                                    348 non-null float64
a_basics/a_p/literacy_classes                                                      348 non-null float64
A06. If VT- which one?                                                             52 non-null object
A07. if VT yes- have the training finished already?                                52 non-null object
A08. If SHG- How long are you a member of your SHG (in months)?                    334 non-null float64
B01a. Female 0-4 years                                                             348 non-null float64
B01b. Male 0-4 years                                                               348 non-null float64
B02a. Female 5-11 years                                                            348 non-null float64
B02b. Males 5-11 years                                                             348 non-null float64
B03a. Females 12-17 years                                                          348 non-null float64
B03b. Males 12-17 years                                                            348 non-null float64
B04a. Females 18-59 years                                                          348 non-null float64
B04b. Males 18-59 years                                                            348 non-null float64
B05a. Female 60+ years                                                             348 non-null float64
B05b. Males 60+ years                                                              348 non-null float64
B06. How many of your female household members are of the age of 15-24 years?      348 non-null float64
B06. How many of your female household members are of the age of 15-24 years?.1    348 non-null float64
hh_male                                                                            348 non-null float64
hh_female                                                                          348 non-null float64
hh_total                                                                           348 non-null float64
hh_eligbilefem                                                                     348 non-null float64
hh_girls                                                                           348 non-null float64
hh_boys                                                                            348 non-null float64
hh_lit_female                                                                      348 non-null float64
hh_lit_male                                                                        348 non-null float64
a_hh                                                                               347 non-null object
dtypes: float64(24), object(8)
memory usage: 87.1+ KB

In [6]:
herat_basics['a_hh'].value_counts() #identical values, not useful for analysis
herat_basics.drop('a_hh', axis=1, inplace=True)

In [7]:
# rename cols for readibility & practicality 
##(enum_id, loc_herat > more generic names that work both for Jbad & Herat)
basic_cols = ['city','enum','loc','gender','activities','activities.shgs','activities.vt',
                'activities.lit_class','vt_type','vt_training_complete','shg_mbr_since_mth',
                'f_0-4','m_0-4','f_5-11','m_5-11','f_12-17','m_12-17', 'f_18-59','m_18-59',
                'f_over60','m_over60', 'm_hh','f_hh','tot_hh','f_15-24','m_15-24',
                 'f_eligble_hh','f_lit_hh','m_lit_hh','girl_hh','boy_hh'
                ]
herat_basics = clean_df(herat_basics, basic_cols)

city ['herat']
enum ['Irshad', 'Fatima_Tawhid_Jabrahil', 'Somaya', 'Tawfiq', 'Ahmad', 'Fatima_Charahi', 'Sonita', 'Raihana', 'Aria_Sadaqat', 'Manizha']
loc ['Tawhid_Jebrahil', 'Arq_Naw_Kharqi_Mobarak', 'Mahal_Rafaa', 'Saeed_Ghanad', 'Brotharan', 'Bakhshi_az_Hawz_Sultan', 'Bagh_Karbasi_2', 'Esar_Hawz_Karbas', 'Khaja_Rokhband', 'Mashkwaniya', 'Arbab_Zadaha', 'Baraman_Bologh_Baraman', 'Kochi_Abdul_Raziq_Khan_Charkh_Taban', 'Guzar_Gul_Bahar_Guzar_Do_Dalan', 'Guzar_Hawzi_Sultan', 'Mahal_Wardaka', 'Baghchi_Roghani', 'Guzar_Naw_Bahae', 'Hauz_e_Malik_Jade_Khaja_Amin', 'Guzar_Hama_Sakina']
gender ['male', 'female']
activities ['shgs', 'shgs vt', 'shgs literacy_classes', 'shgs vt literacy_classes', 'literacy_classes', 'vt']
activities.shgs [1, 0]
activities.vt [0, 1]
activities.lit_class [0, 1]
vt_type [-1, 'mobile_phones_repair', 'tailoring', 'ac_fridge_repair', 'electrical_wiring', 'cookie_baking', 'beautiy_parlor', 'embroidery_by_machin']
vt_training_complete [-1, 'yes', 'no']
shg_mbr_since_mth [12, 15, 5, 7, 6, 13, 4, -1, 16, 10, 8, 17, 14, 2, 9, 11, 3, 1, 18]
f_0-4 [0, 1, 3, 2, 8, 4]
m_0-4 [0, 2, 1, 11, 3]
f_5-11 [1, 0, 2, 4, 3, 6]
m_5-11 [1, 0, 2, 6, 3]
f_12-17 [0, 1, 2, 8, 3, 4]
m_12-17 [0, 1, 3, 2]
f_18-59 [1, 2, 4, 3, 5, 0, 8, 7, 9]
m_18-59 [1, 5, 3, 4, 2, 0, 6, 7]
f_over60 [1, 0]
m_over60 [0, 1]
m_hh [1, 2, 0, 3, 4, 5]
f_hh [0, 3, 2, 1, 4]
tot_hh [2, 5, 3, 4, 6, 1, 15, 9, 7, 8, 14, 13]
f_15-24 [3, 5, 2, 4, 6, 1, 10, 7, 8, 0, 9, 16, 19, 11, 15]
m_15-24 [5, 8, 10, 7, 6, 12, 4, 9, 14, 13, 3, 11, 2, 19, 15, 25, 28, 16, 17, 22, 20]
f_eligble_hh [1, 2, 4, 3, 5, 0, 11, 9, 6, 7, 8, 12]
f_lit_hh [1, 0, 2, 3, 5, 4, 12, 6, 7]
m_lit_hh [1, 0, 2, 4, 3, 5, 7]
girl_hh [2, 5, 1, 3, 4, 0, 12, 10, 6, 8, 7]
boy_hh [1, 5, 2, 4, 3, 6, 7, 0]

#### 2. Origin
The null values in the data are linked to a 'yes'/1 answer to the first question.
It makes sense that if the family is originally from Herat, the rest of the questions were skipped. 
We'll find the same behaviour in the next section, displacement.

In [8]:
herat_origin = df.loc[:,"C01a.Is your family orignaly from  Herat city?":'c_origin/c01c/other']
herat_origin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 15 columns):
C01a.Is your family orignaly from  Herat city?                                   348 non-null object
C02a.Which province/country did you come to "herat city/jalalabad city" from?    137 non-null object
C01b. Since when are you living in the present location?                         137 non-null object
C02b. When Exactly you come to live here , please state as year/Month            137 non-null datetime64[ns]
C01c. What were the main reasons for choosing to settle in ${city}?              137 non-null object
It's close to the place where we used to live                                    137 non-null float64
It's safe here                                                                   137 non-null float64
We have family/friends/relatives here                                            137 non-null float64
To access better jobs/economic opportunities                                     137 non-null float64
To access better education                                                       137 non-null float64
To access better health services                                                 137 non-null float64
We heard of assistance being given in this location                              137 non-null float64
Our community leader told us to come here                                        137 non-null float64
Government told us to come here                                                  137 non-null float64
c_origin/c01c/other                                                              137 non-null float64
dtypes: datetime64[ns](1), float64(10), object(4)
memory usage: 40.9+ KB

In [9]:
herat_origin['c_origin/c01c/other'].value_counts() #predominantly the same value, not useful in analysis
herat_origin.drop('c_origin/c01c/other', axis=1, inplace = True)

In [10]:
# rename cols for readibility 
origin_cols = ['from_city','came_to_city_from','time_in_city',
    'arrived_to_city','why_city','why_city.proximity','why_city.safety',
    'why_city.relatives','why_city.economics','why_city.education',
    'why_city.health','why_city.assistance','why_city.leader',
    'why_city.gvt']

herat_origin = clean_df(herat_origin, origin_cols)

from_city [0, 1]
came_to_city_from ['ghazni', -1, 'Herat', 'bamyan', 'ghor', 'nimroz', 'paktika', 'farah', 'badghis', 'herat', 'kabul', 'faryab', 'nangarhar', 'kandahar', 'kunduz', 'daykundi', 'urozgan', 'wardak', 'zabul']
time_in_city ['More than 3 years', -1, 'Between 1-3 years']
arrived_to_city [Timestamp('2012-09-01 00:00:00'), Timestamp('2011-09-01 00:00:00'), -1, Timestamp('2012-03-01 00:00:00'), Timestamp('2005-03-01 00:00:00'), Timestamp('2002-11-01 00:00:00'), Timestamp('1997-05-01 00:00:00'), Timestamp('2007-11-01 00:00:00'), Timestamp('2010-09-01 00:00:00'), Timestamp('2003-01-01 00:00:00'), Timestamp('2007-10-01 00:00:00'), Timestamp('1994-11-01 00:00:00'), Timestamp('2007-04-01 00:00:00'), Timestamp('1999-08-01 00:00:00'), Timestamp('2013-10-01 00:00:00'), Timestamp('2010-11-01 00:00:00'), Timestamp('2004-07-01 00:00:00'), Timestamp('2009-10-01 00:00:00'), Timestamp('2009-09-01 00:00:00'), Timestamp('2004-11-01 00:00:00'), Timestamp('2011-11-01 00:00:00'), Timestamp('2014-04-01 00:00:00'), Timestamp('2010-06-01 00:00:00'), Timestamp('1990-07-01 00:00:00'), Timestamp('2003-11-01 00:00:00'), Timestamp('2009-02-01 00:00:00'), Timestamp('1992-11-01 00:00:00'), Timestamp('2015-10-01 00:00:00'), Timestamp('2005-09-01 00:00:00'), Timestamp('1997-07-01 00:00:00'), Timestamp('2013-09-01 00:00:00'), Timestamp('1997-06-01 00:00:00'), Timestamp('2013-02-01 00:00:00'), Timestamp('2008-01-01 00:00:00'), Timestamp('2009-12-01 00:00:00'), Timestamp('2000-02-01 00:00:00'), Timestamp('2005-07-01 00:00:00'), Timestamp('2002-10-01 00:00:00'), Timestamp('1999-06-01 00:00:00'), Timestamp('2002-07-01 00:00:00'), Timestamp('2004-04-01 00:00:00'), Timestamp('2011-10-01 00:00:00'), Timestamp('1996-09-01 00:00:00'), Timestamp('2007-05-01 00:00:00'), Timestamp('2010-12-01 00:00:00'), Timestamp('2011-12-01 00:00:00'), Timestamp('2014-12-01 00:00:00'), Timestamp('2000-09-01 00:00:00'), Timestamp('2008-11-01 00:00:00'), Timestamp('2012-01-01 00:00:00'), Timestamp('2004-01-01 00:00:00'), Timestamp('2004-06-01 00:00:00'), Timestamp('2007-12-01 00:00:00'), Timestamp('2003-08-01 00:00:00'), Timestamp('2000-05-01 00:00:00'), Timestamp('2000-08-01 00:00:00'), Timestamp('2012-11-01 00:00:00'), Timestamp('2001-10-01 00:00:00'), Timestamp('2006-08-01 00:00:00'), Timestamp('2009-11-01 00:00:00'), Timestamp('2015-09-01 00:00:00'), Timestamp('2003-10-01 00:00:00'), Timestamp('2014-11-01 00:00:00'), Timestamp('2011-03-01 00:00:00'), Timestamp('2012-05-01 00:00:00'), Timestamp('2009-08-01 00:00:00'), Timestamp('1982-05-01 00:00:00'), Timestamp('2011-08-01 00:00:00'), Timestamp('2012-04-01 00:00:00'), Timestamp('2007-09-01 00:00:00'), Timestamp('2010-07-01 00:00:00'), Timestamp('2012-07-01 00:00:00'), Timestamp('2015-02-01 00:00:00'), Timestamp('2005-08-01 00:00:00'), Timestamp('2014-05-01 00:00:00'), Timestamp('2003-12-01 00:00:00'), Timestamp('2002-09-01 00:00:00'), Timestamp('2005-10-01 00:00:00'), Timestamp('2008-03-01 00:00:00'), Timestamp('2014-03-01 00:00:00'), Timestamp('2008-12-01 00:00:00'), Timestamp('2012-08-01 00:00:00'), Timestamp('2001-01-01 00:00:00'), Timestamp('2013-01-01 00:00:00'), Timestamp('2004-12-01 00:00:00'), Timestamp('2010-05-01 00:00:00'), Timestamp('2008-08-01 00:00:00'), Timestamp('2013-05-01 00:00:00'), Timestamp('2013-11-01 00:00:00'), Timestamp('2010-02-01 00:00:00'), Timestamp('2012-10-01 00:00:00')]
why_city ['pull_jobs other', 'pull_jobs', -1, 'pull_safe', 'other', 'pull_health', 'pull_safe pull_education', 'pull_safe pull_relatives', 'pull_relatives', 'pull_safe pull_jobs pull_education', 'pull_safe pull_jobs pull_education pull_health', 'pull_jobs pull_education', 'pull_relatives pull_leader pull_gov', 'pull_education pull_health', 'pull_relatives pull_education pull_health', 'pull_safe pull_jobs', 'pull_relatives pull_jobs', 'pull_jobs pull_education other', 'pull_safe pull_relatives pull_jobs', 'pull_education', 'pull_safe pull_education pull_health', 'pull_jobs pull_health', 'pull_safe pull_jobs pull_health', 'pull_relatives pull_jobs pull_education', 'pull_close pull_jobs', 'pull_close pull_jobs pull_education', 'pull_relatives pull_education', 'pull_close pull_safe pull_education']
why_city.proximity [0, -1, 1]
why_city.safety [0, -1, 1]
why_city.relatives [0, -1, 1]
why_city.economics [1, -1, 0]
why_city.education [0, -1, 1]
why_city.health [0, -1, 1]
why_city.assistance [0, -1]
why_city.leader [0, -1, 1]
why_city.gvt [0, -1, 1]

#### 3. Displacement

In [11]:
herat_displacement = df.loc[:,'D01. What are the reasons for your displacement?':'D05. What is your preferred choice for the future?']
herat_displacement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 13 columns):
D01. What are the reasons for your displacement?      137 non-null object
Armed conflict                                        137 non-null float64
Military operation                                    137 non-null float64
Indimidation and harrasment                           137 non-null float64
Inter-tribal or factional fighting                    137 non-null float64
Land dispute/Land occupation                          137 non-null float64
Blood feud                                            137 non-null float64
Presence of mines, IEDs or other UXOs/ERW             137 non-null float64
Cross border shelling                                 137 non-null float64
Natural disaster                                      137 non-null float64
Lack of economic opportunities                        137 non-null float64
d_idps/d01/other                                      137 non-null float64
D05. What is your preferred choice for the future?    137 non-null object
dtypes: float64(11), object(2)
memory usage: 35.4+ KB

In [12]:
herat_displacement['d_idps/d01/other'].value_counts() #mostly identical values 
herat_displacement.drop('d_idps/d01/other', axis=1, inplace=True)

In [13]:
displacement_cols = ['displacement_why','displacement_why.armed_conflicts',
                    'displacement_why.military','displacement_why.harasst',
                     'displacement_why.tribal','displacement_why.land','displacement_why.blood_fd',
                    'displacement_why.mines','displacement_why.x_border_shell','displacement_why.nat_disast',
                     'displacement_why.eco','fut_preference'
                    ]

herat_displacement = clean_df(herat_displacement, displacement_cols)

displacement_why ['dis_land dis_economic', 'dis_economic', -1, 'dis_armed', 'dis_mines', 'other', 'dis_tribal', 'dis_armed dis_economic', 'dis_intimidation dis_tribal', 'dis_tribal dis_mines dis_economic', 'dis_mines dis_naturaldis dis_economic', 'dis_armed dis_military', 'dis_mines dis_economic', 'dis_armed dis_mines dis_economic', 'dis_armed dis_economic other', 'dis_shelling', 'dis_military dis_mines', 'dis_naturaldis dis_economic', 'dis_feud dis_economic', 'dis_shelling dis_economic', 'dis_intimidation dis_mines dis_economic', 'dis_tribal dis_economic', 'dis_intimidation dis_economic']
displacement_why.armed_conflicts [0, -1, 1]
displacement_why.military [0, -1, 1]
displacement_why.harasst [0, -1, 1]
displacement_why.tribal [0, -1, 1]
displacement_why.land [1, 0, -1]
displacement_why.blood_fd [0, -1, 1]
displacement_why.mines [0, -1, 1]
displacement_why.x_border_shell [0, -1, 1]
displacement_why.nat_disast [0, -1, 1]
displacement_why.eco [1, -1, 0]
fut_preference ['fut_stay', -1, 'fut_move', 'fut_return', 'move_abroad']

#### 4. Food

In [14]:
herat_food  = df.loc[:,'E01. Rice, bread, potatoes, maize':"E34a. How often did this happen?"]
herat_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 42 columns):
E01. Rice, bread, potatoes, maize                                                                                                                                                   348 non-null float64
E02. Beans, peas, chickpeas, peanuts, cashew nuts, nut                                                                                                                              348 non-null float64
E03. All vegetables                                                                                                                                                                 348 non-null float64
E04. All fruits                                                                                                                                                                     348 non-null float64
E05. Beef, goat, poultry, eggs, fish, sheep                                                                                                                                         348 non-null float64
E06. Milk, yoghurt, other dairy products                                                                                                                                            348 non-null float64
E07. Sugar, and sugar products, honey                                                                                                                                               348 non-null float64
E08. Oil, fats and butter                                                                                                                                                           348 non-null float64
E09. Spices, tea, salt, coffee, small amounts of milk for tea                                                                                                                       348 non-null float64
E11. Bread, rice, noodles, biscuits, or food made of: wheat, rice,                                                                                                                  348 non-null object
E12. Potatoes, or any other food made from roots or tubers                                                                                                                          348 non-null object
E13. Pumpkin, carrots, squash, sweet potatoes that are yellow or orange inside                                                                                                      348 non-null object
E14. Any dark green leafy vegetables such as: leaves, bean leaves, spinach, pepper leaves                                                                                           348 non-null object
E15. Any other vegetables                                                                                                                                                           348 non-null object
E16. Any ripe mangoes, dried apricots or cantalupe                                                                                                                                  348 non-null object
E17. Any other fruits                                                                                                                                                               348 non-null object
E18. Beef, lamb, goat, birds, chicken, ducks, liver kidney, heart or other organ meat                                                                                               348 non-null object
E19. Any eggs?                                                                                                                                                                      348 non-null object
E20. Any fresh and dried fish?                                                                                                                                                      348 non-null object
E21. Any food made from beans, peas, lentils or nuts                                                                                                                                348 non-null object
E22. Any cheese, yoghurt, milk, or other milk product                                                                                                                               348 non-null object
E23. Any food made with oil, fat or butter                                                                                                                                          348 non-null object
E24. Any sugar or honey                                                                                                                                                             348 non-null object
E25. Any condiments, coffe, tea                                                                                                                                                     348 non-null object
E26. In the past 4 weeks, did you worry that your household would have enough food?                                                                                                 348 non-null object
E26a. How often did this happen?                                                                                                                                                    226 non-null object
E27. In the past 4 weeks, were you or any household member not able to eat the kinds of foods you preferred, because of lack of resources?                                          348 non-null object
E27a. How often did this happen?                                                                                                                                                    251 non-null object
E38. In the past 4 weeks, did you or any household member have to eat a limited variety of foods, due to a lack of resources?                                                       348 non-null object
E28a. How often did this happen?                                                                                                                                                    182 non-null object
E29. In the past 4 weeks, did you or any household member have to eat some foods that you really did not want to eat because of lack of resources to obtain other types of food?    348 non-null object
E29a. How often did this happen?                                                                                                                                                    245 non-null object
E30. In the past 4 weeks, did you or any household member have to eat a smaller meal than you felt you needed because there was not enough food?                                    348 non-null object
E30a. How often did this happen?                                                                                                                                                    169 non-null object
E31. In the past 4 weeks, did you or any other household member have to eat fewer meals in a day because there was not enough food?                                                 348 non-null object
E31a. How often did this happen?                                                                                                                                                    138 non-null object
E32. In the past 4 weeks, was there ever no food to eat of any kind in your household because of lack of resources to get food?                                                     348 non-null object
E32a. How often did this happen?                                                                                                                                                    85 non-null object
E33. In the past 4 weeks, did you or any household member go to sleep at night hungry because there was not enough food?                                                            348 non-null object
E33a. How often did this happen?                                                                                                                                                    68 non-null object
E34. In the past 4 weeks, did you or any household member go a whole day and night without eating anything because there was not enough food?                                       348 non-null object
E34a. How often did this happen?                                                                                                                                                    34 non-null object
dtypes: float64(9), object(33)
memory usage: 114.3+ KB

In [15]:
#Saving the meanings of the food questions -- while we've prefered meaningfull names so far, 
#for speed, simplicity and to compare with baseline/endline, we'll keep abreviations. 
food_meaning = herat_food.columns

#Simplifying/minimizing columns names
food_cols = ['e0'+str(i) for i in range(1,10)] + ['e'+str(i) for i in range(10,27)]

for i in range(27,35):
    food_cols.append('e'+str(i))
    food_cols.append('e'+str(i)+'a')
    
herat_food = clean_df(herat_food, food_cols)

e01 [7, 2, 1, 5, 4, 3, 6]
e02 [0, 2, 1, 5, 4, 7, 3, 6]
e03 [2, 7, 4, 1, 3, 6, 0, 5]
e04 [0, 4, 3, 1, 2, 7, 5, 6]
e05 [1, 3, 7, 2, 0, 4, 5, 6]
e06 [0, 1, 4, 7, 3, 2, 6, 5]
e07 [3, 7, 0, 6, 1, 5, 4, 2]
e08 [7, 6, 1, 0, 4, 3, 5, 2]
e09 [7, 6, 0, 5, 3, 4]
e10 [1, 0]
e11 [0, 1]
e12 [0, 1]
e13 [1, 0]
e14 [0, 1]
e15 [0, 1]
e16 [0, 1]
e17 [0, 1]
e18 [0, 1]
e19 [0, 1]
e20 [0, 1]
e21 [0, 1]
e22 [1, 0]
e23 [0, 1]
e24 [1, 0]
e25 [0, 1]
e26 [-1, 'rarely', 'often', 'sometimes']
e27 [1, 0]
e27a ['rarely', 'often', -1, 'sometimes']
e28 [0, 1]
e28a [-1, 'sometimes', 'rarely', 'often']
e29 [1, 0]
e29a ['sometimes', 'often', -1, 'rarely']
e30 [0, 1]
e30a [-1, 'sometimes', 'rarely', 'often']
e31 [0, 1]
e31a [-1, 'sometimes', 'rarely', 'often']
e32 [0, 1]
e32a [-1, 'rarely', 'sometimes', 'often']
e33 [0, 1]
e33a [-1, 'rarely', 'sometimes', 'often']
e34 [0, 1]
e34a [-1, 'sometimes', 'rarely', 'often']

#### 5. Basic Services

In [16]:
herat_services = df.loc[:,"Household female members over 12 years - How many are literate?":
                         "F09. How many minutes is the next health facility away?"]
herat_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 55 columns):
Household female members over 12 years - How many are literate?                                                                 348 non-null float64
Household Male members over 12 years - How many are literate?                                                                   348 non-null float64
F01a1. What are the main reasons for illiteracy of female household members?                                                    243 non-null object
 family restrictions                                                                                                            243 non-null float64
no need to read/write                                                                                                           243 non-null float64
financial issues                                                                                                                243 non-null float64
school too far                                                                                                                  243 non-null float64
language problems in existing school                                                                                            243 non-null float64
Tazkera / enrollment problem                                                                                                    243 non-null float64
they have to work to earn money                                                                                                 243 non-null float64
they have to help at home                                                                                                       243 non-null float64
no time                                                                                                                         243 non-null float64
f_access/f_lit/f01a1/other                                                                                                      243 non-null float64
F01b1. What are the main reasons for illiteracy of male household members?                                                      192 non-null object
 family restrictions.1                                                                                                          192 non-null float64
no need to read/write.1                                                                                                         192 non-null float64
financial issues.1                                                                                                              192 non-null float64
school too far.1                                                                                                                192 non-null float64
language problems in existing school.1                                                                                          192 non-null float64
Tazkera / enrollment problem.1                                                                                                  192 non-null float64
they have to work to earn money.1                                                                                               192 non-null float64
they have to help at home.1                                                                                                     192 non-null float64
no time.1                                                                                                                       192 non-null float64
f_access/f_lit/f01b1/other                                                                                                      192 non-null float64
F02b. What is the level of education of the person with the highest level of education in the HH?                               348 non-null object
F03. Do you have electricity in your house?                                                                                     348 non-null object
F04. What is the main source for drinking water?                                                                                348 non-null object
F04a. Is the source for driking water in your compound?                                                                         346 non-null object
F04b. How many minutes does it take to bring drinking water to the house?                                                       14 non-null object
F05. Is your water clean?                                                                                                       348 non-null object
F06. What kind of latrines do the members of your household mainly use?                                                         348 non-null object
F06b. Are you sharing the latrine with another household?                                                                       348 non-null object
F07. Does everyone in the household have a tazkera?                                                                             348 non-null object
F07a1. Does the head of HH have tazkera?                                                                                        348 non-null object
F07b. have  you or your relatives obtained a tazkera since you joined this project (thanks to the project  support)?  Y/n/dk    348 non-null object
F07b1. do you know how to obtain a tazkera (thanks to the project support)?  y/n/dk                                             348 non-null object
F07c. Your household has ${hh_female} female members, how many of them have a tazkera?                                          122 non-null float64
F07c1. Why do not all female members have a tazkera?                                                                            107 non-null object
Not useful                                                                                                                      107 non-null float64
Not yet needed (person too young)                                                                                               107 non-null float64
Too expensive (bribe)                                                                                                           107 non-null float64
I don’t know whom to approach/how to get it                                                                                     107 non-null float64
The process is too lengthy                                                                                                      107 non-null float64
Not at the place of origin                                                                                                      107 non-null float64
f_access/f07a1/other                                                                                                            107 non-null float64
F07d1. Your household has ${hh_male} male members, how many of them have a tazkera?                                             122 non-null float64
F07d2. Why do not all male members have a tazkera?                                                                              67 non-null object
Not useful.1                                                                                                                    67 non-null float64
Not yet needed (person too young).1                                                                                             67 non-null float64
Too expensive (bribe).1                                                                                                         67 non-null float64
I don’t know whom to approach/how to get it.1                                                                                   67 non-null float64
The process is too lengthy.1                                                                                                    67 non-null float64
Not at the place of origin.1                                                                                                    67 non-null float64
f_access/f07b1/other                                                                                                            67 non-null float64
F09. How many minutes is the next health facility away?                                                                         348 non-null object
dtypes: float64(38), object(17)
memory usage: 149.6+ KB

In [17]:
services_cols = ['f_12_lit_hh', 'm_12_lit_hh', 'f_illit', 
                 'f_illit.family','f_illit.no_need',
                 'f_illit.financial','f_illit.school_far',
                 'f_illit.language_pb','f_illit.tazkera',
                 'f_illit.make_money','f_illit.help',
                 'f_illit.time','f_illit.other',
                 'm_illit', 'm_illit.family','m_illit.no_need',
                 'm_illit.financial','m_illit.school_far',
                 'm_illit.language_pb','m_illit.tazkera',
                 'm_illit.make_money','m_illit.help',
                 'm_illit.time','m_illit.other',
                 'highest_edu','house_elec',
                 'house_water_source','water_in_compound','water_time',
                 'water_clean','latrine_type', 'share_latrine',
                 'tazkera_all','tazkera_hh_head','tazkera_project','tazkera_howto_project',
                 'f_tazkera','f_no_tazkera' ,'f_no_tazkera.not_useful',
                 'f_no_tazkera.young', 'f_no_tazkera.expensive', 'f_no_tazkera.knowledge',
                 'f_no_tazkera.lengthy', 'f_no_tazkera.origin','f_no_tazkera.other',
                 'm_tazkera','m_no_tazkera', 'm_no_tazkera.not_useful',
                 'm_no_tazkera.young', 'm_no_tazkera.expensive', 'm_no_tazkera.knowledge',
                 'm_no_tazkera.lengthy', 'm_no_tazkera.origin','m_no_tazkera.other',
                 'time_health_facitility']

herat_services = clean_df(herat_services, services_cols)

f_12_lit_hh [2, 1, 4, 3, 0, 5, 6, 7]
m_12_lit_hh [1, 5, 4, 2, 0, 3, 7, 6]
f_illit [-1, 'family_restrictions', 'no_need_read_write financial_issues', 'have_to_work_2_earn_money', 'have_to_help_home', 'no_time', 'financial_issues school_too_far', 'family_restrictions financial_issues', 'family_restrictions financial_issues school_too_far', 'language_problems Tazkera_enrollment_problem', 'family_restrictions have_to_work_2_earn_money', 'financial_issues have_to_work_2_earn_money', 'no_need_read_write', 'language_problems have_to_help_home no_time', 'financial_issues', 'school_too_far have_to_work_2_earn_money no_time', 'school_too_far have_to_work_2_earn_money', 'school_too_far no_time', 'school_too_far', 'school_too_far have_to_help_home', 'have_to_work_2_earn_money have_to_help_home', 'financial_issues have_to_help_home', 'family_restrictions no_time', 'financial_issues no_time', 'financial_issues school_too_far Tazkera_enrollment_problem', 'language_problems have_to_work_2_earn_money', 'family_restrictions school_too_far have_to_help_home', 'financial_issues school_too_far no_time', 'family_restrictions have_to_help_home', 'other', 'family_restrictions other', 'have_to_help_home no_time', 'family_restrictions school_too_far', 'family_restrictions financial_issues no_time', 'no_need_read_write have_to_help_home', 'family_restrictions financial_issues have_to_help_home', 'school_too_far other', 'financial_issues school_too_far have_to_help_home', 'family_restrictions school_too_far other']
f_illit.family [-1, 1, 0]
f_illit.no_need [-1, 0, 1]
f_illit.financial [-1, 0, 1]
f_illit.school_far [-1, 0, 1]
f_illit.language_pb [-1, 0, 1]
f_illit.tazkera [-1, 0, 1]
f_illit.make_money [-1, 0, 1]
f_illit.help [-1, 0, 1]
f_illit.time [-1, 0, 1]
f_illit.other [-1, 0, 1]
m_illit [-1, 'have_to_work_2_earn_money', 'financial_issues', 'financial_issues have_to_work_2_earn_money', 'financial_issues school_too_far have_to_work_2_earn_money have_to_help_home', 'family_restrictions have_to_work_2_earn_money', 'financial_issues school_too_far', 'language_problems Tazkera_enrollment_problem have_to_work_2_earn_money', 'have_to_work_2_earn_money have_to_help_home', 'no_time', 'financial_issues language_problems have_to_work_2_earn_money have_to_help_home', 'financial_issues have_to_work_2_earn_money have_to_help_home', 'no_need_read_write', 'family_restrictions financial_issues', 'financial_issues have_to_work_2_earn_money no_time', 'school_too_far language_problems no_time', 'language_problems', 'financial_issues no_time', 'financial_issues have_to_help_home', 'no_need_read_write no_time', 'have_to_work_2_earn_money no_time', 'other', 'have_to_work_2_earn_money other', 'financial_issues other', 'no_need_read_write have_to_work_2_earn_money', 'school_too_far have_to_work_2_earn_money', 'financial_issues school_too_far no_time', 'school_too_far no_time', 'school_too_far', 'have_to_help_home', 'family_restrictions', 'family_restrictions school_too_far']
m_illit.family [-1, 0, 1]
m_illit.no_need [-1, 0, 1]
m_illit.financial [-1, 0, 1]
m_illit.school_far [-1, 0, 1]
m_illit.language_pb [-1, 0, 1]
m_illit.tazkera [-1, 0, 1]
m_illit.make_money [-1, 1, 0]
m_illit.help [-1, 0, 1]
m_illit.time [-1, 0, 1]
m_illit.other [-1, 0, 1]
highest_edu ['primary_school', 'high_school', 'university', 'secondary_school', 'college_diploma', 'no_scholing', 'post_grad', 'madrassa', 'other']
house_elec [1, 0]
house_water_source ['water_impr', 'other', 'water_tank', 'water_unimpr']
water_in_compound ['yes', 'no', -1]
water_time [-1, 'min_low', 'min_more', 'min_mid']
water_clean ['w_idk', 'w_bad', 'w_good']
latrine_type ['lat_impr', 'lat_trad', 'lat_none']
share_latrine [0, 1]
tazkera_all [1, 0]
tazkera_hh_head [1, 0]
tazkera_project ['no', 'idk', 'yes']
tazkera_howto_project ['yes', 'no', 'idk']
f_tazkera [-1, 1, 0, 2, 3, 4, 7, 8, 5, 6, 13]
f_no_tazkera [-1, 'taz_origin', 'taz_needed', 'taz_lengthy', 'taz_useful', 'taz_useful taz_needed', 'taz_needed taz_lengthy taz_origin', 'taz_lengthy taz_origin', 'taz_needed taz_lengthy', 'taz_useful taz_needed taz_origin', 'other', 'taz_needed taz_expensive taz_lengthy', 'taz_needed taz_expensive', 'taz_needed taz_origin', 'taz_expensive taz_lengthy', 'taz_expensive', 'taz_knowledge', 'taz_needed other', 'taz_knowledge taz_lengthy']
f_no_tazkera.not_useful [-1, 0, 1]
f_no_tazkera.young [-1, 0, 1]
f_no_tazkera.expensive [-1, 0, 1]
f_no_tazkera.knowledge [-1, 0, 1]
f_no_tazkera.lengthy [-1, 0, 1]
f_no_tazkera.origin [-1, 1, 0]
f_no_tazkera.other [-1, 0, 1]
m_tazkera [-1, 5, 1, 2, 4, 3, 6, 0, 7, 11]
m_no_tazkera [-1, 'taz_lengthy', 'taz_needed', 'taz_origin', 'taz_needed taz_lengthy taz_origin', 'taz_needed taz_lengthy', 'taz_lengthy taz_origin', 'taz_expensive taz_lengthy', 'taz_needed taz_expensive', 'taz_expensive', 'taz_needed taz_expensive taz_lengthy', 'taz_useful', 'taz_knowledge taz_lengthy']
m_no_tazkera.not_useful [-1, 0, 1]
m_no_tazkera.young [-1, 0, 1]
m_no_tazkera.expensive [-1, 0, 1]
m_no_tazkera.knowledge [-1, 0, 1]
m_no_tazkera.lengthy [-1, 1, 0]
m_no_tazkera.origin [-1, 0, 1]
m_no_tazkera.other [-1, 0]
time_health_facitility ['minh_mid', 'minh_low', 'minh_more']

#### 6. Assistance
As with the origin and displacement sections, the answer to the first question determines whether the following are skipped or not.

In [18]:
herat_assistance = df.loc[:,"G01. Has your family ever received any assistance from any organisation or government, the local community or relatives?":
                           "g_social/g01assistance/g03/other"] 
herat_assistance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 14 columns):
G01. Has your family ever received any assistance from any organisation or government, the local community or relatives?    348 non-null object
g_social/g01assistance/g02                                                                                                  165 non-null object
g_social/g01assistance/g02/from_government                                                                                  165 non-null float64
g_social/g01assistance/g02/friend_or_relatives_personal_network                                                             165 non-null float64
g_social/g01assistance/g02/from_organization_NGO_or_UN_agency_both_local_or_international                                   165 non-null float64
g_social/g01assistance/g02/other                                                                                            165 non-null float64
g_social/g01assistance/g03                                                                                                  165 non-null object
Food Aid                                                                                                                    165 non-null float64
NFI (HH items, blankets, tarpaulin, clothes, hygiene items, etc)                                                            165 non-null float64
Health services                                                                                                             165 non-null float64
Housing assistance (rebuilt of shelter, etc)                                                                                165 non-null float64
Legal assistance (advise about rights, procetion, legal matters, etc)                                                       165 non-null float64
Assistance for a job                                                                                                        165 non-null float64
g_social/g01assistance/g03/other                                                                                            165 non-null float64
dtypes: float64(11), object(3)
memory usage: 38.1+ KB

In [19]:
assistance_cols = ['received_assist','assist_from', 'assist_from.gvt','assist_from.personal',
                'assist_from.ngo','assist_from.other',
                'assist_type', 'assist_type.food','assist_type.nfi','assist_type.health','assist_type.housing',
                'assist_type.legal','assist_type.job','assist_type.other']

herat_assistance = clean_df(herat_assistance, assistance_cols)

received_assist [1, 0]
assist_from ['from_organization_NGO_or_UN_agency_both_local_or_international', 'friend_or_relatives_personal_network from_organization_NGO_or_UN_agency_both_local_or_international', -1, 'from_government from_organization_NGO_or_UN_agency_both_local_or_international', 'other', 'friend_or_relatives_personal_network', 'from_government']
assist_from.gvt [0, -1, 1]
assist_from.personal [0, 1, -1]
assist_from.ngo [1, -1, 0]
assist_from.other [0, -1, 1]
assist_type ['assisstance_for_job', 'a_food a_nfi', -1, 'a_legal', 'a_nfi a_health assisstance_for_job', 'a_nfi', 'other', 'a_food', 'a_housing', 'a_food assisstance_for_job', 'a_health', 'a_housing assisstance_for_job']
assist_type.food [0, 1, -1]
assist_type.nfi [0, 1, -1]
assist_type.health [0, -1, 1]
assist_type.housing [0, -1, 1]
assist_type.legal [0, -1, 1]
assist_type.job [1, 0, -1]
assist_type.other [0, -1, 1]

#### 7. Assets

In [20]:
herat_assets = df.loc[:,"H01. What is your present housing arrangement?":
                      "H18. Does the household have the necessary basic hygiene items?"] 
herat_assets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 31 columns):
H01. What is your present housing arrangement?                     348 non-null object
H02. Do you own land?                                              348 non-null object
H03. Do you have a land deed for that land?                        65 non-null object
h_assets/h02/Yes_my_orignal_location                               348 non-null float64
h_assets/h02/Yes_my_present_location                               348 non-null float64
h_assets/h02/no                                                    348 non-null float64
H04. Which livestock does your family own?                         348 non-null object
h_assets/h04/livestock_cattle                                      348 non-null float64
h_assets/h04/livestock_buffalo                                     348 non-null float64
h_assets/h04/livestock_horse                                       348 non-null float64
h_assets/h04/livestock_donkey                                      348 non-null float64
h_assets/h04/livestock_mule                                        348 non-null float64
h_assets/h04/livestock_poultry                                     348 non-null float64
h_assets/h04/livestock_goat                                        348 non-null float64
h_assets/h04/livestock_sheep                                       348 non-null float64
h_assets/h04/other                                                 348 non-null float64
h_assets/h04_other                                                 290 non-null object
H05. Fridge                                                        348 non-null object
H06. Stove/Oven/microwave                                          348 non-null object
H07. TV                                                            348 non-null object
H08. Radio                                                         348 non-null object
H09. VCR/DVD                                                       348 non-null object
H10. Mobile phone                                                  348 non-null object
H11. Computer/Tablet                                               348 non-null object
H12. Sewing machine/Embroidery machine                             348 non-null object
H13. Iron                                                          348 non-null object
H14. Bicycle                                                       348 non-null object
H15. Motorcycle                                                    348 non-null object
H16. Car/Zaranj                                                    348 non-null object
H17. Tractor/Other agricultural machinery                          348 non-null object
H18. Does the household have the necessary basic hygiene items?    348 non-null object
dtypes: float64(12), object(19)
memory usage: 84.4+ KB

In [21]:
assets_cols = ['housing', 'own_land','land_deed','original_loc', 'present_loc',
                 'asset_no','livestock','livestock.cattle','livestock.buffalo','livestock.horse',
                'livestock.donkey','livestock.mule','livestock.poultry','livestock.goat','livestock.sheep',
                'livestock.other','livestock.other2','fridge','stove','tv','radio','dvd','mobile',
                'computer','sewing_mach','iron','bike','moto','car','tractor','basic_hygiene']

herat_assets = clean_df(herat_assets,assets_cols)

housing ['rented_family_house_shered_with_others', 'Other_own home_home_without_paying_rent)', 'other']
own_land ['Yes_my_orignal_location', 'no', 'Yes_my_present_location', 'Yes_my_orignal_location Yes_my_present_location']
land_deed ['deed_idk', 'deed_no', 'deed_informal', -1, 'deed_formal']
original_loc [1, 0]
present_loc [0, 1]
asset_no [0, 1]
livestock ['None', 'livestock_poultry', 'livestock_buffalo', 'livestock_sheep', 'other', 'livestock_buffalo livestock_poultry', 'livestock_poultry livestock_sheep', 'livestock_goat']
livestock.cattle [0]
livestock.buffalo [0, 1]
livestock.horse [0]
livestock.donkey [0]
livestock.mule [0]
livestock.poultry [0, 1]
livestock.goat [0, 1]
livestock.sheep [0, 1]
livestock.other [1, 0]
livestock.other2 [False, -1, 'Fish']
fridge [1, 0]
stove [1, 0]
tv [1, 0]
radio [0, 1]
dvd [0, 1]
mobile [1, 0]
computer [0, 1]
sewing_mach [0, 1]
iron [1, 0]
bike [1, 0]
moto [0, 1]
car [0, 1]
tractor [0, 1]
basic_hygiene [1, 0]

#### 8. Adaptive Capacity

In [22]:
herat_adaptive = df.loc[:,"Does any one in your familly earn income or bring money?":
                       "i_adaptive/i12/other"] 
herat_adaptive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 348 entries, 0 to 347
Data columns (total 56 columns):
Does any one in your familly earn income or bring money?                                                   348 non-null object
I01. How many people are working in the family to earn money?                                              336 non-null float64
I01a. From what sources do they earn an income? (check all that applies/multiple choice)                   336 non-null object
i_adaptive/income_source/salaried_worker_private                                                           336 non-null float64
i_adaptive/income_source/salaried_worker_public                                                            336 non-null float64
i_adaptive/income_source/self_employed_own_business                                                        336 non-null float64
i_adaptive/income_source/employer                                                                          336 non-null float64
i_adaptive/income_source/day_laborer                                                                       336 non-null float64
i_adaptive/income_source/family_worker                                                                     336 non-null float64
i_adaptive/income_source/working_at_home                                                                   336 non-null float64
i_adaptive/income_source/apprentice                                                                        336 non-null float64
i_adaptive/income_source/other                                                                             336 non-null float64
I02.On average, how many days a week did they earn an income?                                              336 non-null float64
I02a. Did they bring home approx. the same amount of income every week/month?                              336 non-null object
I03. What is your average monthly income (entire HH, in AFA)?                                              348 non-null float64
I04.Has your income increased since joining the project?                                                   348 non-null object
I04a. if yes, how much it has increased? (in AFA, monthly average)                                         125 non-null float64
I04b. For VT benefciairies only - Are you currently working/active in the  {VT field they chose} field?    348 non-null object
I04c. if yes, in which form? (multiple choice )                                                            48 non-null object
i_adaptive/if_yes_which_form/Intern                                                                        48 non-null float64
i_adaptive/if_yes_which_form/Employee                                                                      48 non-null float64
i_adaptive/if_yes_which_form/Opened_owb_shop_outside_of_home                                               48 non-null float64
i_adaptive/if_yes_which_form/Opened_own_shop_at_home                                                       48 non-null float64
i_adaptive/if_yes_which_form/Opened_shop_with_other_people                                                 48 non-null float64
i_adaptive/if_yes_which_form/Employer                                                                      48 non-null float64
I05.Are all school-aged children (6-18)  attending school regularly?                                       348 non-null object
I06. How much of your family income is spent on food?                                                      348 non-null object
I07. How much of your family income is spent on fuel and heating?                                          348 non-null object
I08. How much does the family spend daily to go to work?                                                   348 non-null object
I09. How much is your family able to save per month?                                                       348 non-null object
I10. How much is your families present debt in total (excluding SHG loans)?                                348 non-null object
I11. Which of the following vulnerabilities apply to you or your family?                                   348 non-null object
i_adaptive/i11/vul_minor                                                                                   348 non-null float64
i_adaptive/i11/vul_woman                                                                                   348 non-null float64
i_adaptive/i11/vul_sing_male                                                                               348 non-null float64
i_adaptive/i11/vul_sing_female                                                                             348 non-null float64
i_adaptive/i11/vul_ill                                                                                     348 non-null float64
i_adaptive/i11/vul_poor                                                                                    348 non-null float64
i_adaptive/i11/vul_plw                                                                                     348 non-null float64
i_adaptive/i11/vul_drugs                                                                                   348 non-null float64
i_adaptive/i11/vul_old                                                                                     348 non-null float64
i_adaptive/i11/vul_pdisabled                                                                               348 non-null float64
i_adaptive/i11/vul_mdisabled                                                                               348 non-null float64
i_adaptive/i11/vul_medcial                                                                                 348 non-null float64
i_adaptive/i11/vul_special                                                                                 348 non-null float64
i_adaptive/i11/vul_ochildren                                                                               348 non-null float64
i_adaptive/i11/other                                                                                       348 non-null float64
i_adaptive/i11_other                                                                                       56 non-null object
I12. What would have helped you the most in the first six months of your displacement?                     137 non-null object
i_adaptive/i12/a_food                                                                                      137 non-null float64
i_adaptive/i12/a_nfi                                                                                       137 non-null float64
i_adaptive/i12/a_health                                                                                    137 non-null float64
i_adaptive/i12/a_housing                                                                                   137 non-null float64
i_adaptive/i12/a_legal                                                                                     137 non-null float64
i_adaptive/i12/assisstance_for_job                                                                         137 non-null float64
i_adaptive/i12/other                                                                                       137 non-null float64
dtypes: float64(41), object(15)
memory usage: 152.3+ KB

In [23]:
adaptive_cols = ['income_earner','income_earner_hh','income_source',
                 'income_source.salaried_private', 'income_source.salaried_public',
                 'income_source.self_employed','income_source.employer','income_source.day_laborer',
                 'income_source.fam_worker','income_source.home_work','income_source.apprentice','income_source.other',
                'income_days','income_var','avg_mth_income','income_incr_project',
                'income_incr_project_amt','vt_active', 'vt_form','vt_form.intern',
                 'vt_form.employee','vt_form.own_shop_outside','vt_form.own_shop_home',
                 'vt_form.shop_people','vt_form.employer','children_school','spending_food',
                 'spending_fuel','spending_transport','saving','debt','vul',
                 'vul.minor','vul.woman','vul.sing_male','vul.sing_female',
                 'vul.ill','vul.poor','vul.plw','vul.drugs','vul.old','vul.pdisabled',
                 'vul.mdisabled','vul_medical','vul.special','vul.ochildren','vul.other',
                 'vul.other2','helpful_6mth','helpful_6mth.food','helpful_6mth.nfi',
                 'helpful_6mth.health','helpful_6mth.housing','helpful_6mth.legal',
                 'helpful_6mth.job_assist','helpful_6mth.other'
                ]

herat_adaptive = clean_df(herat_adaptive,adaptive_cols)

income_earner ['yes', 'no', 'No']
income_earner_hh [1, 4, 3, 2, 6, -1, 5]
income_source ['day_laborer', 'salaried_worker_private salaried_worker_public self_employed_own_business', 'self_employed_own_business', 'salaried_worker_public', 'apprentice', 'salaried_worker_public self_employed_own_business day_laborer', 'salaried_worker_private', 'salaried_worker_private self_employed_own_business', 'salaried_worker_private day_laborer', 'salaried_worker_public self_employed_own_business', 'working_at_home apprentice', 'self_employed_own_business apprentice', 'self_employed_own_business day_laborer', -1, 'family_worker', 'day_laborer working_at_home', 'working_at_home', 'salaried_worker_private family_worker']
income_source.salaried_private [0, 1, -1]
income_source.salaried_public [0, 1, -1]
income_source.self_employed [0, 1, -1]
income_source.employer [0, -1]
income_source.day_laborer [1, 0, -1]
income_source.fam_worker [0, -1, 1]
income_source.home_work [0, 1, -1]
income_source.apprentice [0, 1, -1]
income_source.other [0, -1]
income_days [4, 3, 6, 7, 0, 5, 1, 2, -1]
income_var ['dnk', 'it_varies_every_week-month', 'less_and_less', 'same', 'more_and_more', -1]
avg_mth_income [6000, 2000, 16500, 20000, 5000, 9000, 8000, 1000, 10000, 15000, 7500, 3000, 50000, 14000, 12000, 8500, 4000, 7200, 1500, 4500, 3500, 30000, 17000, 2500, 2800, 11000, 18000, 7000, 21000, 16000, 13000, 0, 5700, 16280, 60000, 1200, 9500, 70000, 1800, 25000, 1100]
income_incr_project ['no', 'yes', 'idk']
income_incr_project_amt [-1, 5000, 400, 0, 2000, 2200, 2500, 100, 300, 200, 700, 600, 500, 1000, 1600, 3000, 4000, 150, 2100, 1500, 800]
vt_active ['not_aplicable', 'no', 'yes']
vt_form [-1, 'Intern', 'Opened_own_shop_at_home', 'Employee', 'Opened_shop_with_other_people', 'Opened_owb_shop_outside_of_home', 'Opened_owb_shop_outside_of_home Opened_own_shop_at_home']
vt_form.intern [-1, 1, 0]
vt_form.employee [-1, 0, 1]
vt_form.own_shop_outside [-1, 0, 1]
vt_form.own_shop_home [-1, 0, 1]
vt_form.shop_people [-1, 0, 1]
vt_form.employer [-1, 0]
children_school [0, 1]
spending_food ['more_than_half', 'half_or_less', 'all_income']
spending_fuel ['half_or_less', 'all_income', 'more_than_half']
spending_transport ['transport_nothing', 'transport_less', 'transport_more']
saving ['saving_less', 'saving_none', 'saving_more']
debt ['debt_more', 'debt_less', 'debt_mid']
vul ['vul_ill vul_plw vul_old', 'other', 'vul_ochildren', 'vul_poor vul_medcial', 'vul_ill vul_poor vul_pdisabled', 'vul_poor', 'vul_poor vul_old', 'vul_ill other', 'vul_minor', 'vul_woman', 'vul_sing_male vul_sing_female', 'vul_minor vul_woman', 'vul_old', 'vul_sing_female', 'vul_woman vul_plw', 'vul_special', 'vul_woman vul_old', 'vul_ill vul_special', 'vul_mdisabled', 'vul_woman vul_pdisabled', 'vul_pdisabled', 'vul_plw vul_old vul_mdisabled', 'vul_sing_female vul_pdisabled', 'vul_plw vul_pdisabled', 'vul_ill vul_plw', 'vul_drugs vul_pdisabled', 'vul_ill vul_pdisabled', 'vul_sing_male', 'vul_minor vul_sing_male vul_old', 'vul_minor vul_sing_male', 'vul_ill vul_old', 'vul_ill', 'vul_old vul_mdisabled', 'vul_ill vul_poor vul_drugs vul_old vul_pdisabled vul_medcial', 'vul_woman vul_pdisabled vul_mdisabled', 'vul_woman vul_special', 'vul_woman vul_sing_female vul_pdisabled', 'vul_woman vul_ill vul_old vul_special', 'vul_pdisabled vul_ochildren', 'vul_woman vul_pdisabled vul_special', 'vul_woman vul_ill vul_drugs vul_special', 'vul_woman vul_pdisabled vul_ochildren', 'vul_pdisabled vul_medcial', 'vul_poor vul_ochildren', 'vul_ill vul_mdisabled', 'vul_pdisabled vul_special', 'vul_sing_female vul_plw vul_old', 'vul_ill vul_poor vul_pdisabled vul_medcial', 'vul_poor vul_pdisabled vul_ochildren', 'vul_woman vul_ill', 'vul_plw', 'vul_old vul_pdisabled', 'vul_pdisabled vul_mdisabled', 'vul_old vul_pdisabled vul_ochildren', 'vul_ill vul_pdisabled vul_medcial', 'vul_poor vul_plw', 'vul_sing_female vul_plw', 'vul_woman vul_drugs vul_pdisabled vul_mdisabled', 'vul_woman vul_ill vul_special', 'vul_woman vul_sing_female', 'vul_plw vul_ochildren', 'vul_poor other', 'vul_plw vul_old', 'vul_poor vul_old vul_pdisabled', 'vul_old vul_ochildren', 'vul_woman vul_poor', 'vul_poor vul_pdisabled', 'vul_woman vul_special vul_ochildren', 'vul_minor other', 'vul_woman vul_drugs vul_special', 'vul_old vul_mdisabled vul_special', 'vul_drugs', 'vul_sing_male vul_poor', 'vul_poor vul_mdisabled']
vul.minor [0, 1]
vul.woman [0, 1]
vul.sing_male [0, 1]
vul.sing_female [0, 1]
vul.ill [1, 0]
vul.poor [0, 1]
vul.plw [1, 0]
vul.drugs [0, 1]
vul.old [1, 0]
vul.pdisabled [0, 1]
vul.mdisabled [0, 1]
vul_medical [0, 1]
vul.special [0, 1]
vul.ochildren [0, 1]
vul.other [0, 1]
vul.other2 [-1, 'Economy', 'Fales', 'Security problems', 'False', 'Security', 'Concern for future of her child', 'فرزند زیرسن', 'هیچ مشکلی ندارند', 'Unsecurity', 'Unsafety', 'No', 'نا امنی']
helpful_6mth ['a_nfi a_housing assisstance_for_job', 'a_food a_nfi assisstance_for_job', -1, 'assisstance_for_job', 'a_nfi', 'a_legal', 'a_housing assisstance_for_job', 'a_food assisstance_for_job', 'a_nfi a_health a_housing assisstance_for_job', 'a_food a_nfi a_health a_housing assisstance_for_job', 'a_food a_housing assisstance_for_job', 'a_nfi assisstance_for_job', 'a_food a_health assisstance_for_job', 'a_health a_housing assisstance_for_job', 'a_food', 'other', 'a_health assisstance_for_job', 'a_food a_nfi', 'a_food a_nfi a_housing', 'a_nfi a_housing']
helpful_6mth.food [0, 1, -1]
helpful_6mth.nfi [1, -1, 0]
helpful_6mth.health [0, -1, 1]
helpful_6mth.housing [1, 0, -1]
helpful_6mth.legal [0, -1, 1]
helpful_6mth.job_assist [1, -1, 0]
helpful_6mth.other [0, -1, 1]

In [24]:
# dealing with a uppercase 'typo'
herat_adaptive.loc[herat_adaptive['income_earner']=='No','income_earner']='no'
encode_binary(herat_adaptive,'income_earner')
display_df(herat_adaptive)

income_earner [1, 0]
income_earner_hh [1, 4, 3, 2, 6, -1, 5]
income_source ['day_laborer', 'salaried_worker_private salaried_worker_public self_employed_own_business', 'self_employed_own_business', 'salaried_worker_public', 'apprentice', 'salaried_worker_public self_employed_own_business day_laborer', 'salaried_worker_private', 'salaried_worker_private self_employed_own_business', 'salaried_worker_private day_laborer', 'salaried_worker_public self_employed_own_business', 'working_at_home apprentice', 'self_employed_own_business apprentice', 'self_employed_own_business day_laborer', -1, 'family_worker', 'day_laborer working_at_home', 'working_at_home', 'salaried_worker_private family_worker']
income_source.salaried_private [0, 1, -1]
income_source.salaried_public [0, 1, -1]
income_source.self_employed [0, 1, -1]
income_source.employer [0, -1]
income_source.day_laborer [1, 0, -1]
income_source.fam_worker [0, -1, 1]
income_source.home_work [0, 1, -1]
income_source.apprentice [0, 1, -1]
income_source.other [0, -1]
income_days [4, 3, 6, 7, 0, 5, 1, 2, -1]
income_var ['dnk', 'it_varies_every_week-month', 'less_and_less', 'same', 'more_and_more', -1]
avg_mth_income [6000, 2000, 16500, 20000, 5000, 9000, 8000, 1000, 10000, 15000, 7500, 3000, 50000, 14000, 12000, 8500, 4000, 7200, 1500, 4500, 3500, 30000, 17000, 2500, 2800, 11000, 18000, 7000, 21000, 16000, 13000, 0, 5700, 16280, 60000, 1200, 9500, 70000, 1800, 25000, 1100]
income_incr_project ['no', 'yes', 'idk']
income_incr_project_amt [-1, 5000, 400, 0, 2000, 2200, 2500, 100, 300, 200, 700, 600, 500, 1000, 1600, 3000, 4000, 150, 2100, 1500, 800]
vt_active ['not_aplicable', 'no', 'yes']
vt_form [-1, 'Intern', 'Opened_own_shop_at_home', 'Employee', 'Opened_shop_with_other_people', 'Opened_owb_shop_outside_of_home', 'Opened_owb_shop_outside_of_home Opened_own_shop_at_home']
vt_form.intern [-1, 1, 0]
vt_form.employee [-1, 0, 1]
vt_form.own_shop_outside [-1, 0, 1]
vt_form.own_shop_home [-1, 0, 1]
vt_form.shop_people [-1, 0, 1]
vt_form.employer [-1, 0]
children_school [0, 1]
spending_food ['more_than_half', 'half_or_less', 'all_income']
spending_fuel ['half_or_less', 'all_income', 'more_than_half']
spending_transport ['transport_nothing', 'transport_less', 'transport_more']
saving ['saving_less', 'saving_none', 'saving_more']
debt ['debt_more', 'debt_less', 'debt_mid']
vul ['vul_ill vul_plw vul_old', 'other', 'vul_ochildren', 'vul_poor vul_medcial', 'vul_ill vul_poor vul_pdisabled', 'vul_poor', 'vul_poor vul_old', 'vul_ill other', 'vul_minor', 'vul_woman', 'vul_sing_male vul_sing_female', 'vul_minor vul_woman', 'vul_old', 'vul_sing_female', 'vul_woman vul_plw', 'vul_special', 'vul_woman vul_old', 'vul_ill vul_special', 'vul_mdisabled', 'vul_woman vul_pdisabled', 'vul_pdisabled', 'vul_plw vul_old vul_mdisabled', 'vul_sing_female vul_pdisabled', 'vul_plw vul_pdisabled', 'vul_ill vul_plw', 'vul_drugs vul_pdisabled', 'vul_ill vul_pdisabled', 'vul_sing_male', 'vul_minor vul_sing_male vul_old', 'vul_minor vul_sing_male', 'vul_ill vul_old', 'vul_ill', 'vul_old vul_mdisabled', 'vul_ill vul_poor vul_drugs vul_old vul_pdisabled vul_medcial', 'vul_woman vul_pdisabled vul_mdisabled', 'vul_woman vul_special', 'vul_woman vul_sing_female vul_pdisabled', 'vul_woman vul_ill vul_old vul_special', 'vul_pdisabled vul_ochildren', 'vul_woman vul_pdisabled vul_special', 'vul_woman vul_ill vul_drugs vul_special', 'vul_woman vul_pdisabled vul_ochildren', 'vul_pdisabled vul_medcial', 'vul_poor vul_ochildren', 'vul_ill vul_mdisabled', 'vul_pdisabled vul_special', 'vul_sing_female vul_plw vul_old', 'vul_ill vul_poor vul_pdisabled vul_medcial', 'vul_poor vul_pdisabled vul_ochildren', 'vul_woman vul_ill', 'vul_plw', 'vul_old vul_pdisabled', 'vul_pdisabled vul_mdisabled', 'vul_old vul_pdisabled vul_ochildren', 'vul_ill vul_pdisabled vul_medcial', 'vul_poor vul_plw', 'vul_sing_female vul_plw', 'vul_woman vul_drugs vul_pdisabled vul_mdisabled', 'vul_woman vul_ill vul_special', 'vul_woman vul_sing_female', 'vul_plw vul_ochildren', 'vul_poor other', 'vul_plw vul_old', 'vul_poor vul_old vul_pdisabled', 'vul_old vul_ochildren', 'vul_woman vul_poor', 'vul_poor vul_pdisabled', 'vul_woman vul_special vul_ochildren', 'vul_minor other', 'vul_woman vul_drugs vul_special', 'vul_old vul_mdisabled vul_special', 'vul_drugs', 'vul_sing_male vul_poor', 'vul_poor vul_mdisabled']
vul.minor [0, 1]
vul.woman [0, 1]
vul.sing_male [0, 1]
vul.sing_female [0, 1]
vul.ill [1, 0]
vul.poor [0, 1]
vul.plw [1, 0]
vul.drugs [0, 1]
vul.old [1, 0]
vul.pdisabled [0, 1]
vul.mdisabled [0, 1]
vul_medical [0, 1]
vul.special [0, 1]
vul.ochildren [0, 1]
vul.other [0, 1]
vul.other2 [-1, 'Economy', 'Fales', 'Security problems', 'False', 'Security', 'Concern for future of her child', 'فرزند زیرسن', 'هیچ مشکلی ندارند', 'Unsecurity', 'Unsafety', 'No', 'نا امنی']
helpful_6mth ['a_nfi a_housing assisstance_for_job', 'a_food a_nfi assisstance_for_job', -1, 'assisstance_for_job', 'a_nfi', 'a_legal', 'a_housing assisstance_for_job', 'a_food assisstance_for_job', 'a_nfi a_health a_housing assisstance_for_job', 'a_food a_nfi a_health a_housing assisstance_for_job', 'a_food a_housing assisstance_for_job', 'a_nfi assisstance_for_job', 'a_food a_health assisstance_for_job', 'a_health a_housing assisstance_for_job', 'a_food', 'other', 'a_health assisstance_for_job', 'a_food a_nfi', 'a_food a_nfi a_housing', 'a_nfi a_housing']
helpful_6mth.food [0, 1, -1]
helpful_6mth.nfi [1, -1, 0]
helpful_6mth.health [0, -1, 1]
helpful_6mth.housing [1, 0, -1]
helpful_6mth.legal [0, -1, 1]
helpful_6mth.job_assist [1, -1, 0]
helpful_6mth.other [0, -1, 1]

#### 9. Herat Final

In [25]:
herat_mid = pd.concat([herat_basics, herat_origin, herat_displacement, herat_food, 
                         herat_services, herat_assistance, herat_assets, herat_adaptive], 
                        axis = 1)
herat_mid.shape

(348, 255)

In [26]:
herat_mid.tail()

,city,enum,loc,gender,activities,activities.shgs,activities.vt,activities.lit_class,vt_type,vt_training_complete,...,vul.other,vul.other2,helpful_6mth,helpful_6mth.food,helpful_6mth.nfi,helpful_6mth.health,helpful_6mth.housing,helpful_6mth.legal,helpful_6mth.job_assist,helpful_6mth.other
343,herat,Manizha,Guzar_Naw_Bahae,female,shgs,1,0,0,-1,-1,...,0,-1,-1,-1,-1,-1,-1,-1,-1,-1
344,herat,Manizha,Guzar_Naw_Bahae,female,shgs,1,0,0,-1,-1,...,0,-1,-1,-1,-1,-1,-1,-1,-1,-1
345,herat,Manizha,Guzar_Naw_Bahae,female,shgs,1,0,0,-1,-1,...,0,-1,assisstance_for_job,0,0,0,0,0,1,0
346,herat,Ahmad,Baghchi_Roghani,male,shgs vt,1,1,0,mobile_phones_repair,no,...,0,-1,-1,-1,-1,-1,-1,-1,-1,-1
347,herat,Irshad,Bagh_Karbasi_2,male,shgs,1,0,0,-1,-1,...,0,-1,a_food a_nfi a_housing,1,1,0,1,0,0,0

### Jalalabad
#### 1. Basics

In [27]:
df = jlbd

drop_na_df(df)
df.tail()

,start,end,today,city,enumj_id,loc_jbad,a_basics/a02,A05. Which activities do you participate/d in?,a_basics/a_p/shgs,a_basics/a_p/vt,...,i_adaptive/i12/a_legal,i_adaptive/i12/assisstance_for_job,i_adaptive/i12/other,i_adaptive/i12_other,meta/instanceID,_id,_uuid,_submission_time,_index,_parent_index
462,2017-03-20T11:16:53.186Z,2017-03-20T11:21:08.461Z,2017-03-20,jalalabad,Mohibullah,Aqab-e_Qabail_and_Qasaba,male,shgs,True,False,...,NaN,NaN,NaN,NaN,uuid:d0414cc1-8748-4e57-ad31-4670037fd543,7341852,d0414cc1-8748-4e57-ad31-4670037fd543,2017-03-20T10:05:15,463,-1
463,2017-03-20T10:31:00.894+04:30,2017-03-20T10:44:12.083+04:30,2017-03-20,jalalabad,Mohammad_Rauf,Zer_Jumat,male,shgs,True,False,...,NaN,NaN,NaN,NaN,uuid:fb4330f4-5b14-41e5-bc3b-9887ae16bbf1,7341891,fb4330f4-5b14-41e5-bc3b-9887ae16bbf1,2017-03-20T10:06:16,464,-1
464,2017-03-20T10:44:33.512+04:30,2017-03-20T10:57:15.681+04:30,2017-03-20,jalalabad,Mohammad_Rauf,Zer_Jumat,male,shgs,True,False,...,NaN,NaN,NaN,NaN,uuid:67378d06-399f-40c9-a7dd-5df845ef82a7,7341892,67378d06-399f-40c9-a7dd-5df845ef82a7,2017-03-20T10:06:17,465,-1
465,2017-03-20T11:18:30.186Z,2017-03-20T11:29:43.646Z,2017-03-20,jalalabad,Mohammad_Idrees,Camps_to_Hindo_Soozan,male,shgs,True,False,...,0.0,1.0,0.0,NaN,uuid:8811f706-3767-4051-91fb-9aad24db32e2,7341945,8811f706-3767-4051-91fb-9aad24db32e2,2017-03-20T10:09:06,466,-1
466,2017-03-20T09:34:51.557Z,2017-03-20T10:42:59.713Z,2017-03-20,jalalabad,Mohammad_Idrees,Camps_to_Hindo_Soozan,male,shgs vt,True,True,...,0.0,1.0,0.0,NaN,uuid:5e69c1fc-df2d-4bb6-a299-ff052f9a34fe,7341948,5e69c1fc-df2d-4bb6-a299-ff052f9a34fe,2017-03-20T10:09:11,467,-1

In [28]:
jlbd_info = pd.concat([df.iloc[:,0:2], df.iloc[:,-6:]], axis=1) 
jlbd_info

,start,end,meta/instanceID,_id,_uuid,_submission_time,_index,_parent_index
0,2017-03-16T12:31:38.302+04:30,2017-03-16T12:39:29.669+04:30,uuid:0d0ac60c-6824-40f2-a5c0-f223babd2a2e,7274730,0d0ac60c-6824-40f2-a5c0-f223babd2a2e,2017-03-16T11:58:03,1,-1
1,2017-03-16T12:22:33.335+04:30,2017-03-16T12:31:29.726+04:30,uuid:af8ed761-1fd9-4afe-b957-ebc139ba9e74,7274728,af8ed761-1fd9-4afe-b957-ebc139ba9e74,2017-03-16T11:58:01,2,-1
2,2017-03-16T12:12:35.376+04:30,2017-03-16T12:22:28.845+04:30,uuid:ebd2d3f9-8280-4357-9fd9-ce140367cddb,7274725,ebd2d3f9-8280-4357-9fd9-ce140367cddb,2017-03-16T11:58:00,3,-1
3,2017-03-16T12:01:33.233+04:30,2017-03-16T12:12:30.601+04:30,uuid:be502dc3-ca79-4a5d-88ab-9f6f2ad64a41,7274724,be502dc3-ca79-4a5d-88ab-9f6f2ad64a41,2017-03-16T11:57:59,4,-1
4,2017-03-16T11:19:39.802+04:30,2017-03-16T11:32:33.069+04:30,uuid:7a9d994b-2606-40b4-b4fd-22cc602c80fb,7274723,7a9d994b-2606-40b4-b4fd-22cc602c80fb,2017-03-16T11:57:57,5,-1
5,2017-03-16T11:09:51.733+04:30,2017-03-16T11:19:27.614+04:30,uuid:0b4a84ba-bf83-460c-b050-9b5917790a63,7274722,0b4a84ba-bf83-460c-b050-9b5917790a63,2017-03-16T11:57:56,6,-1
6,2017-03-16T10:58:00.071+04:30,2017-03-16T11:09:47.065+04:30,uuid:0b195f47-2dbb-4b11-893a-8e57212d3cd8,7274721,0b195f47-2dbb-4b11-893a-8e57212d3cd8,2017-03-16T11:57:55,7,-1
7,2017-03-16T10:46:11.691+04:30,2017-03-16T10:57:55.782+04:30,uuid:4c5ed501-379b-433e-a951-8876f4c8d104,7274720,4c5ed501-379b-433e-a951-8876f4c8d104,2017-03-16T11:57:54,8,-1
8,2017-03-07T12:11:18.411+04:30,2017-03-07T12:46:18.466+04:30,uuid:8ec5ca30-0a6d-4e60-bdd5-2bee5f143b26,7041524,8ec5ca30-0a6d-4e60-bdd5-2bee5f143b26,2017-03-07T11:21:15,9,-1
9,2017-03-07T13:03:05.086+04:30,2017-03-07T16:00:44.978+04:30,uuid:dd023ad7-4486-4469-8701-7211f9c0eb95,7042127,dd023ad7-4486-4469-8701-7211f9c0eb95,2017-03-07T11:30:58,10,-1
10,2017-03-07T09:56:03.698+04:30,2017-03-07T12:30:49.625+04:30,uuid:92839ec0-dd7d-4984-bdbc-7996f4bd3220,7042865,92839ec0-dd7d-4984-bdbc-7996f4bd3220,2017-03-07T11:58:26,11,-1
11,2017-03-07T12:31:14.226+04:30,2017-03-07T13:12:11.255+04:30,uuid:42c3ff85-ce16-4be6-b0bb-ace180b7c2fa,7042867,42c3ff85-ce16-4be6-b0bb-ace180b7c2fa,2017-03-07T11:58:27,12,-1
12,2017-03-06T10:33:51.225Z,2017-03-07T10:24:25.679Z,uuid:e59ea8b9-b5f3-418b-8997-6409e180d561,7043017,e59ea8b9-b5f3-418b-8997-6409e180d561,2017-03-07T12:07:59,13,-1
13,2017-03-07T06:25:42.274Z,2017-03-07T06:50:15.328Z,uuid:34f9325a-e177-427c-8391-6969b1f914fa,7043018,34f9325a-e177-427c-8391-6969b1f914fa,2017-03-07T12:08:00,14,-1
14,2017-03-07T07:05:39.819Z,2017-03-07T07:34:45.079Z,uuid:002135c5-9eee-407b-bbd9-9148698eb175,7043019,002135c5-9eee-407b-bbd9-9148698eb175,2017-03-07T12:08:01,15,-1
15,2017-03-07T07:37:29.627Z,2017-03-07T07:56:22.143Z,uuid:24b9bb43-8f49-4b3a-9535-dbbbbd71c584,7043020,24b9bb43-8f49-4b3a-9535-dbbbbd71c584,2017-03-07T12:08:03,16,-1
16,2017-03-07T07:56:29.053Z,2017-03-07T08:26:06.817Z,uuid:08d70df5-1c03-46f8-b66e-47941956e2e9,7043021,08d70df5-1c03-46f8-b66e-47941956e2e9,2017-03-07T12:08:04,17,-1
17,2017-03-07T09:52:01.614+04:30,2017-03-07T16:42:52.229+04:30,uuid:fd75cc75-f2a4-43e4-92ea-99b71eab238e,7043177,fd75cc75-f2a4-43e4-92ea-99b71eab238e,2017-03-07T12:16:02,18,-1
18,2017-03-07T11:11:59.158+04:30,2017-03-07T16:43:48.341+04:30,uuid:11cf0c5f-30fa-4d84-ad6c-90daab411df1,7043178,11cf0c5f-30fa-4d84-ad6c-90daab411df1,2017-03-07T12:16:04,19,-1
19,2017-03-07T11:36:36.143+04:30,2017-03-07T16:45:19.984+04:30,uuid:3f3d3d9c-6282-417b-af5b-17ccb5f58a4c,7043179,3f3d3d9c-6282-417b-af5b-17ccb5f58a4c,2017-03-07T12:16:05,20,-1
20,2017-03-07T12:17:41.524+04:30,2017-03-07T16:44:45.096+04:30,uuid:64206727-d32c-4e6e-a723-d92bd42b9e7e,7043180,64206727-d32c-4e6e-a723-d92bd42b9e7e,2017-03-07T12:16:07,21,-1
21,2017-03-07T12:36:23.152+04:30,2017-03-07T16:44:28.126+04:30,uuid:b600ec54-3b80-427d-9f92-14455f948068,7043182,b600ec54-3b80-427d-9f92-14455f948068,2017-03-07T12:16:08,22,-1
22,2017-03-07T06:23:33.628Z,2017-03-07T07:02:17.122Z,uuid:04b8f07d-a2a5-4d7d-8b80-677f16a940c4,7043198,04b8f07d-a2a5-4d7d-8b80-677f16a940c4,2017-03-07T12:18:10,23,-1
23,2017-03-07T07:02:46.025Z,2017-03-07T07:34:39.720Z,uuid:c9330a3e-5e21-4993-8bbb-ee981b650b51,7043199,c9330a3e-5e21-4993-8bbb-ee981b650b51,2017-03-07T12:18:11,24,-1
24,2017-03-07T07:35:30.048Z,2017-03-07T08:01:19.695Z,uuid:c190bdc5-c2be-4e01-861b-2f6f773ce0db,7043201,c190bdc5-c2be-4e01-861b-2f6f773ce0db,2017-03-07T12:18:12,25,-1
25,2017-03-07T08:01:39.019Z,2017-03-07T08:23:43.931Z,uuid:51a0289c-60e8-4e2c-b6bc-d3781bafa38e,7043203,51a0289c-60e8-4e2c-b6bc-d3781bafa38e,2017-03-07T12:18:13,26,-1
26,2017-03-07T08:25:27.834Z,2017-03-07T08:48:35.849Z,uuid:e43f4b58-2c87-4c50-acd0-7820d314ca5b,7043205,e43f4b58-2c87-4c50-acd0-7820d314ca5b,2017-03-07T12:18:15,27,-1
27,2017-03-07T08:48:46.945Z,2017-03-07T09:04:48.948Z,uuid:bdd1cad8-a008-4883-9474-79d60025347f,7043206,bdd1cad8-a008-4883-9474-79d60025347f,2017-03-07T12:18:16,28,-1
28,2017-03-07T10:48:20.164+04:30,2017-03-07T12:35:22.838+04:30,uuid:2137dc86-a549-41c0-b613-4ed74122839f,7043244,2137dc86-a549-41c0-b613-4ed74122839f,2017-03-07T12:21:27,29,-1
29,2017-03-07T11:36:27.327+04:30,2017-03-07T12:36:06.131+04:30,uuid:d53308de-2b6e-4b48-b7d4-b48c6e0a4b48,7043245,d53308de-2b6e-4b48-b7d4-b48c6e0a4b48,2017-03-07T12:21:28,30,-1
...,...,...,...,...,...,...,...,...
437,2017-03-19T06:12:41.993Z,2017-03-19T06:25:18.333Z,uuid:be9c7fd8-f568-4fbb-bc94-d4c39c82fe07,7325368,be9c7fd8-f568-4fbb-bc94-d4c39c82fe07,2017-03-19T11:58:41,438,-1
438,2017-03-19T06:02:29.217Z,2017-03-19T06:10:09.623Z,uuid:69224bb0-5d63-4b60-b537-0248e90841e2,7325390,69224bb0-5d63-4b60-b537-0248e90841e2,2017-03-19T11:59:34,439,-1
439,2017-03-19T06:10:14.425Z,2017-03-19T06:17:24.766Z,uuid:ee50ec43-46a3-42a5-a46c-198b80550517,7325393,ee50ec43-46a3-42a5-a46c-198b80550517,2017-03-19T11:59:36,440,-1
440,2017-03-19T06:17:28.738Z,2017-03-19T06:24:55.657Z,uuid:ba2de139-5d95-4c95-b77c-04baf28a0259,7325394,ba2de139-5d95-4c95-b77c-04baf28a0259,2017-03-19T11:59:38,441,-1
441,2017-03-19T06:33:39.529Z,2017-03-19T06:44:06.419Z,uuid:cd250066-2422-4cb5-85e9-1a78a667bed7,7325396,cd250066-2422-4cb5-85e9-1a78a667bed7,2017-03-19T11:59:39,442,-1
442,2017-03-19T10:35:28.805+04:30,2017-03-19T10:51:32.558+04:30,uuid:0c60e17a-fcb1-474f-92e3-ef4b1bf945eb,7325410,0c60e17a-fcb1-474f-92e3-ef4b1bf945eb,2017-03-19T12:00:17,443,-1
443,2017-03-19T10:51:51.102+04:30,2017-03-19T11:03:07.170+04:30,uuid:50607d4b-5e48-4a38-b61e-730721c26a0f,7325411,50607d4b-5e48-4a38-b61e-730721c26a0f,2017-03-19T12:00:19,444,-1
444,2017-03-19T11:03:17.976+04:30,2017-03-19T11:09:57.394+04:30,uuid:4d0c93cc-37da-4122-b5d7-3d35770ef5eb,7325412,4d0c93cc-37da-4122-b5d7-3d35770ef5eb,2017-03-19T12:00:20,445,-1
445,2017-03-19T11:24:19.918+04:30,2017-03-19T11:35:00.944+04:30,uuid:f4b1b405-8e50-415c-9ebf-da3bcd016cf0,7325413,f4b1b405-8e50-415c-9ebf-da3bcd016cf0,2017-03-19T12:00:22,446,-1
446,2017-03-19T11:35:05.552+04:30,2017-03-19T11:43:52.080+04:30,uuid:d577d752-ff0b-4405-8366-7af0a85826ca,7325414,d577d752-ff0b-4405-8366-7af0a85826ca,2017-03-19T12:00:24,447,-1
447,2017-03-20T11:08:10.000+04:30,2017-03-20T13:21:57.984+04:30,uuid:cca5ccc2-c8ee-4fe4-a4bf-89338073909f,7341674,cca5ccc2-c8ee-4fe4-a4bf-89338073909f,2017-03-20T10:00:20,448,-1
448,2017-03-20T11:10:27.989+04:30,2017-03-20T13:22:44.615+04:30,uuid:e0800d61-2fe8-4db4-bccf-1184cbb38e9b,7341676,e0800d61-2fe8-4db4-bccf-1184cbb38e9b,2017-03-20T10:00:22,449,-1
449,2017-04-03T04:46:55.378Z,2017-04-03T05:48:48.824Z,uuid:32a929b8-8c7e-42d5-9b70-ac316e73567e,7341702,32a929b8-8c7e-42d5-9b70-ac316e73567e,2017-03-20T10:01:53,450,-1
450,2017-03-20T06:28:26.310Z,2017-03-20T06:58:47.900Z,uuid:8ebf96dc-1c6a-4dd1-81b0-4243b499e52f,7341708,8ebf96dc-1c6a-4dd1-81b0-4243b499e52f,2017-03-20T10:02:08,451,-1
451,2017-03-20T06:59:19.746Z,2017-03-20T07:12:48.015Z,uuid:0e0ddfad-ee19-4e2d-bfe4-32ba23ef2b4e,7341712,0e0ddfad-ee19-4e2d-bfe4-32ba23ef2b4e,2017-03-20T10:02:13,452,-1
452,2017-03-20T07:25:53.017Z,2017-03-20T07:34:14.716Z,uuid:312763c0-391c-4c9e-a766-e9694092c1bc,7341715,312763c0-391c-4c9e-a766-e9694092c1bc,2017-03-20T10:02:18,453,-1
453,2017-03-20T07:42:19.780Z,2017-03-20T07:54:35.251Z,uuid:c52beb07-858d-4451-b607-caddccde9bb0,7341721,c52beb07-858d-4451-b607-caddccde9bb0,2017-03-20T10:02:19,454,-1
454,2017-03-20T10:16:52.573+04:30,2017-03-20T14:32:37.234+04:30,uuid:7705bdcb-a0b5-4a6a-9049-85cb17d3be7b,7341731,7705bdcb-a0b5-4a6a-9049-85cb17d3be7b,2017-03-20T10:03:01,455,-1
455,2017-03-20T10:48:22.596+04:30,2017-03-20T14:32:27.699+04:30,uuid:014f915e-3988-4aab-9f85-2d55ef647af7,7341733,014f915e-3988-4aab-9f85-2d55ef647af7,2017-03-20T10:03:02,456,-1
456,2017-03-20T11:10:28.062+04:30,2017-03-20T14:32:20.776+04:30,uuid:077bd325-ea68-4b56-8f8c-ea4f3cb75b3c,7341734,077bd325-ea68-4b56-8f8c-ea4f3cb75b3c,2017-03-20T10:03:04,457,-1
457,2017-03-20T11:19:18.577+04:30,2017-03-20T14:32:13.926+04:30,uuid:900e932f-fd15-4ab8-b603-05389fa711a9,7341735,900e932f-fd15-4ab8-b603-05389fa711a9,2017-03-20T10:03:05,458,-1
458,2017-03-20T10:36:02.184Z,2017-03-20T10:44:53.229Z,uuid:895f9022-15a2-4785-8189-26be721e3348,7341837,895f9022-15a2-4785-8189-26be721e3348,2017-03-20T10:05:07,459,-1
459,2017-03-20T10:45:25.457Z,2017-03-20T10:51:12.645Z,uuid:282b5b2f-3e71-4647-bc92-a84f4638bdd3,7341842,282b5b2f-3e71-4647-bc92-a84f4638bdd3,2017-03-20T10:05:09,460,-1
460,2017-03-20T10:56:15.799Z,2017-03-20T11:00:36.879Z,uuid:df4ad098-f268-47e1-b96c-6863d02099a6,7341845,df4ad098-f268-47e1-b96c-6863d02099a6,2017-03-20T10:05:10,461,-1
461,2017-03-20T11:01:00.784Z,2017-03-20T11:12:53.999Z,uuid:628e85ce-66bf-4d13-97dc-171989162ff9,7341849,628e85ce-66bf-4d13-97dc-171989162ff9,2017-03-20T10:05:12,462,-1
462,2017-03-20T11:16:53.186Z,2017-03-20T11:21:08.461Z,uuid:d0414cc1-8748-4e57-ad31-4670037fd543,7341852,d0414cc1-8748-4e57-ad31-4670037fd543,2017-03-20T10:05:15,463,-1
463,2017-03-20T10:31:00.894+04:30,2017-03-20T10:44:12.083+04:30,uuid:fb4330f4-5b14-41e5-bc3b-9887ae16bbf1,7341891,fb4330f4-5b14-41e5-bc3b-9887ae16bbf1,2017-03-20T10:06:16,464,-1
464,2017-03-20T10:44:33.512+04:30,2017-03-20T10:57:15.681+04:30,uuid:67378d06-399f-40c9-a7dd-5df845ef82a7,7341892,67378d06-399f-40c9-a7dd-5df845ef82a7,2017-03-20T10:06:17,465,-1
465,2017-03-20T11:18:30.186Z,2017-03-20T11:29:43.646Z,uuid:8811f706-3767-4051-91fb-9aad24db32e2,7341945,8811f706-3767-4051-91fb-9aad24db32e2,2017-03-20T10:09:06,466,-1
466,2017-03-20T09:34:51.557Z,2017-03-20T10:42:59.713Z,uuid:5e69c1fc-df2d-4bb6-a299-ff052f9a34fe,7341948,5e69c1fc-df2d-4bb6-a299-ff052f9a34fe,2017-03-20T10:09:11,467,-1

In [29]:
jlbd_basics = df.loc[:,'city':'a_hh']
jlbd_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 32 columns):
city                                                                               467 non-null object
enumj_id                                                                           467 non-null object
loc_jbad                                                                           467 non-null object
a_basics/a02                                                                       467 non-null object
A05. Which activities do you participate/d in?                                     467 non-null object
a_basics/a_p/shgs                                                                  467 non-null bool
a_basics/a_p/vt                                                                    467 non-null bool
a_basics/a_p/literacy_classes                                                      467 non-null bool
A06. If VT- which one?                                                             65 non-null object
A07. if VT yes- have the training finished already?                                65 non-null object
A08. If SHG- How long are you a member of your SHG (in months)?                    354 non-null float64
B01a. Female 0-4 years                                                             467 non-null int64
B01b. Male 0-4 years                                                               467 non-null int64
B02a. Female 5-11 years                                                            467 non-null int64
B02b. Males 5-11 years                                                             467 non-null int64
B03a. Females 12-17 years                                                          467 non-null int64
B03b. Males 12-17 years                                                            467 non-null int64
B04a. Females 18-59 years                                                          467 non-null int64
B04b. Males 18-59 years                                                            467 non-null int64
B05a. Female 60+ years                                                             467 non-null int64
B05b. Males 60+ years                                                              467 non-null int64
B06. How many of your female household members are of the age of 15-24 years?      467 non-null int64
B06. How many of your female household members are of the age of 15-24 years?.1    467 non-null int64
hh_male                                                                            467 non-null int64
hh_female                                                                          467 non-null int64
hh_total                                                                           467 non-null int64
hh_eligbilefem                                                                     467 non-null int64
hh_girls                                                                           467 non-null int64
hh_boys                                                                            467 non-null int64
hh_lit_female                                                                      467 non-null int64
hh_lit_male                                                                        467 non-null int64
a_hh                                                                               463 non-null object
dtypes: bool(3), float64(1), int64(20), object(8)
memory usage: 107.3+ KB

In [30]:
jlbd_basics['a_hh'].value_counts()

OK    463
Name: a_hh, dtype: int64

In [31]:
jlbd_basics.drop('a_hh', axis=1, inplace=True) #same value everywhere, not useful in analysis

jlbd_basics = clean_df(jlbd_basics, basic_cols) #using the same column names as for herat

city ['jalalabad']
enum ['Bakhtmeena', 'Mohammad_Rauf', 'Karishma', 'Abida', 'Roqia', 'Basira', 'Khalida', 'Gulalai', 'Mohibullah', 'Mohammad_Idrees']
loc ['Baboran_2', 'Aqab-e_Qabail_and_Qasaba', 'Khan_Abad', 'Base_e_Guliabad', 'Camps_to_Hindo_Soozan', 'Etahad_Meina', 'Base_e_Ekmalati_1', 'Majboor_Abad_Kochano_Qala', 'West_of_Dokan_Mushko', 'Camps_part_4', 'Narnge_Bagh', 'Base_e_Ekmalati_2', 'Chashma_Khanje', 'Zer_Jumat', 'Etefaq_Road', 'Dokan_Hi_Mushko', 'Roshan_Meina', 'Tawohed_Abad_2', 'Masjed_Sangai', 'Back_of_Qabail_Directorate']
gender ['female', 'male']
activities ['shgs', 'shgs literacy_classes', 'vt', 'literacy_classes', 'shgs vt', 'vt literacy_classes', 'shgs vt literacy_classes']
activities.shgs [1, 0]
activities.vt [0, 1]
activities.lit_class [0, 1]
vt_type [-1, 'ac_fridge_repair', 'tailoring', 'embroidery_by_hand', 'embroidery_by_machin', 'carpentry', 'electrical_wiring', 'mobile_phones_repair', 'beautiy_parlor']
vt_training_complete [-1, 'yes', 'no']
shg_mbr_since_mth [12, -1, 11, 10, 3, 9, 6, 1, 15, 13, 14, 7, 8, 18, 5, 24, 16, 25]
f_0-4 [0, 3, 2, 1, 13, 6, 5, 10, 4, 8, 7]
m_0-4 [1, 3, 0, 2, 4, 8, 6, 5, 15]
f_5-11 [0, 4, 1, 2, 3, 6, 5]
m_5-11 [0, 2, 1, 3, 4, 5, 8, 6]
f_12-17 [2, 1, 0, 3, 4]
m_12-17 [0, 3, 2, 1, 4, 10]
f_18-59 [1, 5, 2, 4, 7, 0, 3, 8, 6, 11]
m_18-59 [1, 2, 3, 5, 0, 4, 7, 6, 12]
f_over60 [1, 0, 2, 5]
m_over60 [1, 0, 2]
m_hh [2, 4, 1, 0, 5, 3, 10, 6]
f_hh [0, 1, 3, 2, 5, 4, 6, 7]
tot_hh [3, 9, 7, 5, 4, 13, 8, 10, 2, 1, 6, 17, 22, 15, 16, 12, 14, 0, 11, 21, 18, 25]
f_15-24 [4, 8, 11, 7, 6, 10, 16, 3, 2, 5, 14, 12, 13, 9, 20, 1, 0, 15, 18, 25, 17]
m_15-24 [7, 17, 18, 11, 14, 9, 10, 13, 29, 12, 8, 5, 15, 21, 25, 6, 22, 38, 24, 36, 4, 2, 28, 3, 23, 27, 19, 16, 26, 20, 46, 37, 32, 35, 34, 45]
f_eligble_hh [3, 7, 4, 1, 2, 9, 8, 6, 5, 0, 10, 12, 11]
f_lit_hh [2, 6, 3, 1, 4, 0, 5, 8, 10]
m_lit_hh [0, 5, 1, 3, 6, 2, 4, 9, 10, 8, 11]
girl_hh [4, 7, 5, 6, 2, 3, 9, 13, 1, 0, 8, 10, 11]
boy_hh [2, 6, 3, 1, 4, 9, 5, 0, 8, 10, 7, 15, 11, 12]

In [32]:
# specific case
jlbd_basics['vt_training_complete'].value_counts()

-1     402
yes     43
no      22
Name: vt_training_complete, dtype: int64

In [33]:
jlbd_basics.loc[jlbd_basics['vt_training_complete']=='yes','vt_training_complete'] =1
jlbd_basics.loc[jlbd_basics['vt_training_complete']=='no','vt_training_complete'] =0
jlbd_basics['vt_training_complete'].value_counts()

-1    402
 1     43
 0     22
Name: vt_training_complete, dtype: int64

#### 2. Origin

In [34]:
jlbd_origin = df.loc[:,"C01a.Is your family orignaly from  Jalalabad city?":
                     'c_origin/c01d/other']
jlbd_origin.info() #c_origin/c01d/other #Government told us to come here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 15 columns):
C01a.Is your family orignaly from  Jalalabad city?                               467 non-null object
C02a.Which province/country did you come to "herat city/jalalabad city" from?    101 non-null object
C01b. Since when are you living in the present location?                         101 non-null object
C02b. When Exactly you come to live here , please state as year/Month            101 non-null datetime64[ns]
C01c. What were the main reasons for choosing to settle in ${city}?              101 non-null object
It's close to the place where we used to live                                    101 non-null float64
It's safe here                                                                   101 non-null float64
We have family/friends/relatives here                                            101 non-null float64
To access better jobs/economic opportunities                                     101 non-null float64
To access better education                                                       101 non-null float64
To access better health services                                                 101 non-null float64
We heard of assistance being given in this location                              101 non-null float64
Our community leader told us to come here                                        101 non-null float64
Government told us to come here                                                  101 non-null float64
c_origin/c01d/other                                                              101 non-null float64
dtypes: datetime64[ns](1), float64(10), object(4)
memory usage: 54.8+ KB

In [35]:
jlbd_origin['c_origin/c01d/other'].value_counts()

0.0    100
1.0      1
Name: c_origin/c01d/other, dtype: int64

In [36]:
jlbd_origin.drop('c_origin/c01d/other',axis=1,inplace=True) #predominant value 

jlbd_origin = clean_df(jlbd_origin, origin_cols)

from_city [1, 0]
came_to_city_from [-1, 'nangarhar', 'kunar', 'nooristan', 'laghman', 'logar', 'herat', 'pakistan', 'kandahar']
time_in_city [-1, 'loc_3', 'loc_1-3', 'loc_1']
arrived_to_city [-1, Timestamp('2013-03-01 00:00:00'), Timestamp('1996-03-01 00:00:00'), Timestamp('2013-01-01 00:00:00'), Timestamp('2017-03-01 00:00:00'), Timestamp('2011-01-01 00:00:00'), Timestamp('1974-03-01 00:00:00'), Timestamp('2007-11-01 00:00:00'), Timestamp('1999-03-01 00:00:00'), Timestamp('2006-03-01 00:00:00'), Timestamp('1984-03-01 00:00:00'), Timestamp('1973-01-01 00:00:00'), Timestamp('1973-02-01 00:00:00'), Timestamp('1996-08-01 00:00:00'), Timestamp('1997-03-01 00:00:00'), Timestamp('2002-10-01 00:00:00'), Timestamp('1998-03-01 00:00:00'), Timestamp('2007-03-01 00:00:00'), Timestamp('2014-02-01 00:00:00'), Timestamp('2014-12-01 00:00:00'), Timestamp('2014-10-01 00:00:00'), Timestamp('2012-03-01 00:00:00'), Timestamp('2002-01-01 00:00:00'), Timestamp('1995-03-01 00:00:00'), Timestamp('1986-03-01 00:00:00'), Timestamp('2009-03-01 00:00:00'), Timestamp('2000-03-01 00:00:00'), Timestamp('1990-03-01 00:00:00'), Timestamp('2007-07-01 00:00:00'), Timestamp('1994-03-01 00:00:00'), Timestamp('2007-06-01 00:00:00'), Timestamp('2003-11-01 00:00:00'), Timestamp('2016-09-01 00:00:00'), Timestamp('1960-10-01 00:00:00'), Timestamp('2012-12-01 00:00:00'), Timestamp('2007-10-01 00:00:00'), Timestamp('2004-08-01 00:00:00'), Timestamp('1998-05-01 00:00:00'), Timestamp('2016-12-01 00:00:00'), Timestamp('2004-01-01 00:00:00'), Timestamp('2001-03-01 00:00:00'), Timestamp('2008-06-01 00:00:00'), Timestamp('2012-11-01 00:00:00'), Timestamp('1988-03-01 00:00:00'), Timestamp('2008-03-01 00:00:00'), Timestamp('2014-03-01 00:00:00'), Timestamp('1991-08-01 00:00:00'), Timestamp('2001-09-01 00:00:00'), Timestamp('1991-05-01 00:00:00'), Timestamp('1996-09-01 00:00:00'), Timestamp('2015-06-01 00:00:00'), Timestamp('2015-01-01 00:00:00'), Timestamp('2014-01-01 00:00:00'), Timestamp('1991-03-01 00:00:00'), Timestamp('2017-04-01 00:00:00'), Timestamp('1943-06-01 00:00:00'), Timestamp('1964-10-01 00:00:00')]
why_city [-1, 'pull_close pull_safe pull_relatives pull_jobs pull_education pull_health', 'other', 'pull_close pull_safe', 'pull_education', 'pull_gov', 'pull_safe', 'pull_jobs', 'pull_jobs pull_education pull_health pull_assistance', 'pull_close pull_safe pull_jobs pull_education', 'pull_jobs pull_education pull_health', 'pull_jobs pull_education pull_gov', 'pull_relatives pull_jobs pull_education pull_health', 'pull_relatives pull_education pull_health', 'pull_safe pull_jobs pull_education', 'pull_health', 'pull_safe pull_jobs pull_education pull_health', 'pull_education pull_health', 'pull_safe pull_education', 'pull_jobs pull_health', 'pull_assistance pull_gov', 'pull_education other', 'pull_safe pull_relatives', 'pull_relatives', 'pull_close pull_safe pull_relatives pull_jobs pull_education', 'pull_close', 'pull_safe pull_jobs', 'pull_relatives pull_jobs pull_education', 'pull_safe pull_jobs pull_health', 'pull_relatives pull_jobs pull_health', 'pull_close pull_education', 'pull_close pull_jobs pull_health', 'pull_safe pull_education pull_health']
why_city.proximity [-1, 1, 0]
why_city.safety [-1, 1, 0]
why_city.relatives [-1, 1, 0]
why_city.economics [-1, 1, 0]
why_city.education [-1, 1, 0]
why_city.health [-1, 1, 0]
why_city.assistance [-1, 0, 1]
why_city.leader [-1, 0]
why_city.gvt [-1, 0, 1]

#### 3. Displacement

In [37]:
jlbd_displacement = df.loc[:,'D01. What are the reasons for your displacement?':
                           'D05. What is your preferred choice for the future?']

jlbd_displacement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 13 columns):
D01. What are the reasons for your displacement?      101 non-null object
Armed conflict                                        101 non-null float64
Military operation                                    101 non-null float64
Indimidation and harrasment                           101 non-null float64
Inter-tribal or factional fighting                    101 non-null float64
Land dispute/Land occupation                          101 non-null float64
Blood feud                                            101 non-null float64
Presence of mines, IEDs or other UXOs/ERW             101 non-null float64
Cross border shelling                                 101 non-null float64
Natural disaster                                      101 non-null float64
Lack of economic opportunities                        101 non-null float64
d_idps/d01/other                                      101 non-null float64
D05. What is your preferred choice for the future?    101 non-null object
dtypes: float64(11), object(2)
memory usage: 47.5+ KB

In [38]:
jlbd_displacement['d_idps/d01/other'].value_counts()

0.0    98
1.0     3
Name: d_idps/d01/other, dtype: int64

In [39]:
jlbd_displacement.drop('d_idps/d01/other', axis=1, inplace=True)

jlbd_displacement = clean_df(jlbd_displacement, displacement_cols)

displacement_why [-1, 'dis_armed dis_naturaldis', 'dis_armed', 'dis_military', 'dis_economic', 'dis_tribal', 'dis_feud', 'dis_naturaldis dis_economic', 'dis_armed dis_economic other', 'dis_tribal dis_economic', 'dis_armed dis_economic', 'dis_economic other', 'dis_intimidation', 'other', 'dis_armed dis_naturaldis dis_economic', 'dis_armed dis_military dis_economic', 'dis_armed dis_shelling dis_economic', 'dis_armed dis_land dis_economic', 'dis_armed dis_mines', 'dis_armed dis_military dis_mines', 'dis_armed dis_military dis_feud', 'dis_armed dis_intimidation', 'dis_armed dis_military dis_intimidation', 'dis_armed dis_military', 'dis_armed dis_feud dis_economic']
displacement_why.armed_conflicts [-1, 1, 0]
displacement_why.military [-1, 0, 1]
displacement_why.harasst [-1, 0, 1]
displacement_why.tribal [-1, 0, 1]
displacement_why.land [-1, 0, 1]
displacement_why.blood_fd [-1, 0, 1]
displacement_why.mines [-1, 0, 1]
displacement_why.x_border_shell [-1, 0, 1]
displacement_why.nat_disast [-1, 1, 0]
displacement_why.eco [-1, 0, 1]
fut_preference [-1, 'fut_stay', 'other', 'fut_return']

#### 4. Food

In [40]:
jlbd_food = df.loc[:,'E01. Rice, bread, potatoes, maize':"E34a. How often did this happen?"]
jlbd_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 42 columns):
E01. Rice, bread, potatoes, maize                                                                                                                                                   467 non-null int64
E02. Beans, peas, chickpeas, peanuts, cashew nuts, nut                                                                                                                              467 non-null int64
E03. All vegetables                                                                                                                                                                 467 non-null int64
E04. All fruits                                                                                                                                                                     467 non-null int64
E05. Beef, goat, poultry, eggs, fish, sheep                                                                                                                                         467 non-null int64
E06. Milk, yoghurt, other dairy products                                                                                                                                            467 non-null int64
E07. Sugar, and sugar products, honey                                                                                                                                               467 non-null int64
E08. Oil, fats and butter                                                                                                                                                           467 non-null int64
E09. Spices, tea, salt, coffee, small amounts of milk for tea                                                                                                                       467 non-null int64
E11. Bread, rice, noodles, biscuits, or food made of: wheat, rice,                                                                                                                  467 non-null object
E12. Potatoes, or any other food made from roots or tubers                                                                                                                          467 non-null object
E13. Pumpkin, carrots, squash, sweet potatoes that are yellow or orange inside                                                                                                      467 non-null object
E14. Any dark green leafy vegetables such as: leaves, bean leaves, spinach, pepper leaves                                                                                           467 non-null object
E15. Any other vegetables                                                                                                                                                           467 non-null object
E16. Any ripe mangoes, dried apricots or cantalupe                                                                                                                                  467 non-null object
E17. Any other fruits                                                                                                                                                               467 non-null object
E18. Beef, lamb, goat, birds, chicken, ducks, liver kidney, heart or other organ meat                                                                                               467 non-null object
E19. Any eggs?                                                                                                                                                                      467 non-null object
E20. Any fresh and dried fish?                                                                                                                                                      467 non-null object
E21. Any food made from beans, peas, lentils or nuts                                                                                                                                467 non-null object
E22. Any cheese, yoghurt, milk, or other milk product                                                                                                                               467 non-null object
E23. Any food made with oil, fat or butter                                                                                                                                          467 non-null object
E24. Any sugar or honey                                                                                                                                                             467 non-null object
E25. Any condiments, coffe, tea                                                                                                                                                     467 non-null object
E26. In the past 4 weeks, did you worry that your household would have enough food?                                                                                                 467 non-null object
E26a. How often did this happen?                                                                                                                                                    348 non-null object
E27. In the past 4 weeks, were you or any household member not able to eat the kinds of foods you preferred, because of lack of resources?                                          467 non-null object
E27a. How often did this happen?                                                                                                                                                    358 non-null object
E38. In the past 4 weeks, did you or any household member have to eat a limited variety of foods, due to a lack of resources?                                                       467 non-null object
E28a. How often did this happen?                                                                                                                                                    327 non-null object
E29. In the past 4 weeks, did you or any household member have to eat some foods that you really did not want to eat because of lack of resources to obtain other types of food?    467 non-null object
E29a. How often did this happen?                                                                                                                                                    335 non-null object
E30. In the past 4 weeks, did you or any household member have to eat a smaller meal than you felt you needed because there was not enough food?                                    467 non-null object
E30a. How often did this happen?                                                                                                                                                    253 non-null object
E31. In the past 4 weeks, did you or any other household member have to eat fewer meals in a day because there was not enough food?                                                 467 non-null object
E31a. How often did this happen?                                                                                                                                                    152 non-null object
E32. In the past 4 weeks, was there ever no food to eat of any kind in your household because of lack of resources to get food?                                                     467 non-null object
E32a. How often did this happen?                                                                                                                                                    109 non-null object
E33. In the past 4 weeks, did you or any household member go to sleep at night hungry because there was not enough food?                                                            467 non-null object
E33a. How often did this happen?                                                                                                                                                    102 non-null object
E34. In the past 4 weeks, did you or any household member go a whole day and night without eating anything because there was not enough food?                                       467 non-null object
E34a. How often did this happen?                                                                                                                                                    86 non-null object
dtypes: int64(9), object(33)
memory usage: 153.3+ KB

In [41]:
jlbd_food = clean_df(jlbd_food, food_cols)

e01 [7, 3, 1, 0, 2, 4, 5, 6]
e02 [2, 4, 1, 5, 3, 0, 6, 7]
e03 [3, 2, 4, 1, 6, 7, 0, 5]
e04 [0, 2, 1, 3, 5, 7, 6, 4]
e05 [0, 1, 2, 3, 4, 6, 5, 7]
e06 [0, 1, 7, 2, 3, 5, 4, 6]
e07 [7, 3, 4, 6, 0, 2, 1, 5]
e08 [7, 1, 4, 0, 3, 2, 5, 6]
e09 [7, 3, 4, 6, 1, 2, 0, 5]
e10 [1, 0]
e11 [1, 0]
e12 [0, 1]
e13 [1, 0]
e14 [0, 1]
e15 [0, 1]
e16 [0, 1]
e17 [0, 1]
e18 [0, 1]
e19 [0, 1]
e20 [1, 0]
e21 [0, 1]
e22 [1, 0]
e23 [1, 0]
e24 [1, 0]
e25 [1, 0]
e26 ['often', 'rarely', -1, 'sometimes']
e27 [1, 0]
e27a ['often', 'rarely', 'sometimes', -1]
e28 [1, 0]
e28a ['often', 'rarely', -1, 'sometimes']
e29 [1, 0]
e29a ['often', 'sometimes', 'rarely', -1]
e30 [1, 0]
e30a ['often', 'sometimes', -1, 'rarely']
e31 [0, 1]
e31a [-1, 'rarely', 'sometimes', 'often']
e32 [0, 1]
e32a [-1, 'often', 'rarely', 'sometimes']
e33 [0, 1]
e33a [-1, 'sometimes', 'often', 'rarely']
e34 [0, 1]
e34a [-1, 'often', 'sometimes', 'rarely']

#### 5. Basic Services

In [42]:
jlbd_services = df.loc[:,"Household female members over 12 years - How many are literate?":
                         "F09. How many minutes is the next health facility away?"]
jlbd_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 57 columns):
Household female members over 12 years - How many are literate?                                                                 467 non-null int64
Household Male members over 12 years - How many are literate?                                                                   467 non-null int64
F01a1. What are the main reasons for illiteracy of female household members?                                                    310 non-null object
 family restrictions                                                                                                            310 non-null float64
no need to read/write                                                                                                           310 non-null float64
financial issues                                                                                                                310 non-null float64
school too far                                                                                                                  310 non-null float64
language problems in existing school                                                                                            310 non-null float64
Tazkera / enrollment problem                                                                                                    310 non-null float64
they have to work to earn money                                                                                                 310 non-null float64
they have to help at home                                                                                                       310 non-null float64
no time                                                                                                                         310 non-null float64
f_access/f_lit/f01a1/other                                                                                                      310 non-null float64
f_access/f_lit/f01a1_other                                                                                                      10 non-null object
F01b1. What are the main reasons for illiteracy of male household members?                                                      235 non-null object
 family restrictions.1                                                                                                          235 non-null float64
no need to read/write.1                                                                                                         235 non-null float64
financial issues.1                                                                                                              235 non-null float64
school too far.1                                                                                                                235 non-null float64
language problems in existing school.1                                                                                          235 non-null float64
Tazkera / enrollment problem.1                                                                                                  235 non-null float64
they have to work to earn money.1                                                                                               235 non-null float64
they have to help at home.1                                                                                                     235 non-null float64
no time.1                                                                                                                       235 non-null float64
f_access/f_lit/f01b1/other                                                                                                      235 non-null float64
F02b. What is the level of education of the person with the highest level of education in the HH?                               467 non-null object
F03. Do you have electricity in your house?                                                                                     467 non-null object
F04. What is the main source for drinking water?                                                                                467 non-null object
F04a. Is the source for driking water in your compound?                                                                         434 non-null object
F04b. How many minutes does it take to bring drinking water to the house?                                                       87 non-null object
F05. Is your water clean?                                                                                                       467 non-null object
F06. What kind of latrines do the members of your household mainly use?                                                         467 non-null object
F06a. Why do you not have any kind of latrine?                                                                                  35 non-null object
F06b. Are you sharing the latrine with another household?                                                                       467 non-null object
F07. Does everyone in the household have a tazkera?                                                                             467 non-null object
F07a1. Does the head of HH have tazkera?                                                                                        467 non-null object
F07b. have  you or your relatives obtained a tazkera since you joined this project (thanks to the project  support)?  Y/n/dk    467 non-null object
F07b1. do you know how to obtain a tazkera (thanks to the project support)?  y/n/dk                                             467 non-null object
F07c. Your household has ${hh_female} female members, how many of them have a tazkera?                                          183 non-null float64
F07c1. Why do not all female members have a tazkera?                                                                            174 non-null object
Not useful                                                                                                                      174 non-null float64
Not yet needed (person too young)                                                                                               174 non-null float64
Too expensive (bribe)                                                                                                           174 non-null float64
I don’t know whom to approach/how to get it                                                                                     174 non-null float64
The process is too lengthy                                                                                                      174 non-null float64
Not at the place of origin                                                                                                      174 non-null float64
f_access/f07a1/other                                                                                                            174 non-null float64
F07d1. Your household has ${hh_male} male members, how many of them have a tazkera?                                             183 non-null float64
F07d2. Why do not all male members have a tazkera?                                                                              96 non-null object
Not useful.1                                                                                                                    96 non-null float64
Not yet needed (person too young).1                                                                                             96 non-null float64
Too expensive (bribe).1                                                                                                         96 non-null float64
I don’t know whom to approach/how to get it.1                                                                                   96 non-null float64
The process is too lengthy.1                                                                                                    96 non-null float64
Not at the place of origin.1                                                                                                    96 non-null float64
f_access/f07b1/other                                                                                                            96 non-null float64
F09. How many minutes is the next health facility away?                                                                         467 non-null object
dtypes: float64(36), int64(2), object(19)
memory usage: 208.0+ KB

In [43]:
jlbd_services['f_access/f_lit/f01a1_other'].value_counts()#f_access/f_lit/f01a1_other

No                    4
Security              2
Na                    1
She's 3 years old.    1
دیر                   1
Nashta                1
Name: f_access/f_lit/f01a1_other, dtype: int64

In [44]:
jlbd_services.drop('f_access/f_lit/f01a1_other', axis=1, inplace = True)
# Additional column compared to Herat ('no_latrine') 
j_services_cols = ['f_12_lit_hh', 'm_12_lit_hh', 'f_illit', 
                 'f_illit.family','f_illit.no_need',
                 'f_illit.financial','f_illit.school_far',
                 'f_illit.language_pb','f_illit.tazkera',
                 'f_illit.make_money','f_illit.help',
                 'f_illit.time','f_illit.other',
                 'm_illit', 'm_illit.family','m_illit.no_need',
                 'm_illit.financial','m_illit.school_far',
                 'm_illit.language_pb','m_illit.tazkera',
                 'm_illit.make_money','m_illit.help',
                 'm_illit.time','m_illit.other',
                 'highest_edu','house_elec',
                 'house_water_source','water_in_compound','water_time',
                 'water_clean','latrine_type','no_latrine', 'share_latrine',
                 'tazkera_all','tazkera_hh_head','tazkera_project','tazkera_howto_project',
                 'f_tazkera','f_no_tazkera' ,'f_no_tazkera.not_useful',
                 'f_no_tazkera.young', 'f_no_tazkera.expensive', 'f_no_tazkera.knowledge',
                 'f_no_tazkera.lengthy', 'f_no_tazkera.origin','f_no_tazkera.other',
                 'm_tazkera','m_no_tazkera', 'm_no_tazkera.not_useful',
                 'm_no_tazkera.young', 'm_no_tazkera.expensive', 'm_no_tazkera.knowledge',
                 'm_no_tazkera.lengthy', 'm_no_tazkera.origin','m_no_tazkera.other',
                 'time_health_facitility']

jlbd_services = clean_df(jlbd_services, j_services_cols)

f_12_lit_hh [2, 4, 1, 3, 0, 6, 5, 8, 10]
m_12_lit_hh [1, 6, 2, 4, 3, 0, 10, 7, 5, 8, 12]
f_illit ['no_need_read_write financial_issues', -1, 'family_restrictions financial_issues have_to_help_home', 'family_restrictions have_to_help_home', 'family_restrictions financial_issues', 'financial_issues', 'family_restrictions financial_issues school_too_far', 'financial_issues school_too_far', 'no_need_read_write financial_issues school_too_far', 'school_too_far', 'have_to_work_2_earn_money', 'family_restrictions', 'no_need_read_write', 'other', 'family_restrictions financial_issues school_too_far have_to_work_2_earn_money', 'financial_issues school_too_far have_to_help_home no_time', 'have_to_help_home', 'family_restrictions no_need_read_write', 'no_need_read_write financial_issues school_too_far language_problems', 'financial_issues have_to_help_home', 'no_need_read_write financial_issues have_to_help_home', 'financial_issues Tazkera_enrollment_problem have_to_help_home', 'family_restrictions no_need_read_write school_too_far have_to_help_home', 'family_restrictions no_need_read_write financial_issues have_to_help_home', 'family_restrictions no_need_read_write financial_issues', 'no_time', 'financial_issues have_to_work_2_earn_money', 'language_problems have_to_help_home', 'financial_issues school_too_far language_problems', 'no_need_read_write school_too_far language_problems', 'financial_issues no_time', 'family_restrictions school_too_far have_to_help_home', 'no_need_read_write financial_issues have_to_help_home no_time', 'family_restrictions no_time', 'no_need_read_write school_too_far', 'school_too_far language_problems', 'no_need_read_write financial_issues Tazkera_enrollment_problem', 'family_restrictions school_too_far', 'financial_issues language_problems have_to_help_home no_time', 'family_restrictions no_need_read_write have_to_help_home', 'financial_issues have_to_help_home no_time', 'Tazkera_enrollment_problem', 'family_restrictions no_need_read_write school_too_far', 'family_restrictions no_need_read_write have_to_help_home no_time']
f_illit.family [0, -1, 1]
f_illit.no_need [1, -1, 0]
f_illit.financial [1, -1, 0]
f_illit.school_far [0, -1, 1]
f_illit.language_pb [0, -1, 1]
f_illit.tazkera [0, -1, 1]
f_illit.make_money [0, -1, 1]
f_illit.help [0, -1, 1]
f_illit.time [0, -1, 1]
f_illit.other [0, -1, 1]
m_illit ['no_need_read_write have_to_work_2_earn_money', -1, 'family_restrictions financial_issues have_to_work_2_earn_money', 'financial_issues', 'financial_issues school_too_far', 'financial_issues school_too_far Tazkera_enrollment_problem', 'school_too_far', 'family_restrictions', 'financial_issues have_to_work_2_earn_money', 'no_need_read_write financial_issues', 'no_time', 'other', 'no_need_read_write financial_issues have_to_work_2_earn_money', 'financial_issues Tazkera_enrollment_problem have_to_work_2_earn_money no_time', 'family_restrictions no_need_read_write', 'financial_issues school_too_far language_problems', 'family_restrictions no_need_read_write school_too_far', 'no_need_read_write', 'financial_issues have_to_work_2_earn_money no_time', 'financial_issues Tazkera_enrollment_problem have_to_work_2_earn_money', 'have_to_work_2_earn_money', 'no_need_read_write school_too_far Tazkera_enrollment_problem', 'no_need_read_write financial_issues no_time', 'no_need_read_write financial_issues school_too_far', 'no_need_read_write school_too_far', 'financial_issues have_to_help_home', 'financial_issues Tazkera_enrollment_problem', 'school_too_far Tazkera_enrollment_problem', 'family_restrictions school_too_far', 'family_restrictions have_to_help_home', 'financial_issues other', 'no_need_read_write financial_issues language_problems', 'financial_issues school_too_far language_problems Tazkera_enrollment_problem', 'financial_issues language_problems Tazkera_enrollment_problem', 'no_need_read_write financial_issues have_to_work_2_earn_money no_time', 'family_restrictions financial_issues', 'financial_issues language_problems have_to_work_2_earn_money', 'school_too_far language_problems', 'financial_issues have_to_work_2_earn_money have_to_help_home no_time', 'no_need_read_write financial_issues have_to_help_home no_time']
m_illit.family [0, -1, 1]
m_illit.no_need [1, -1, 0]
m_illit.financial [0, -1, 1]
m_illit.school_far [0, -1, 1]
m_illit.language_pb [0, -1, 1]
m_illit.tazkera [0, -1, 1]
m_illit.make_money [1, -1, 0]
m_illit.help [0, -1, 1]
m_illit.time [0, -1, 1]
m_illit.other [0, -1, 1]
highest_edu ['no_scholing', 'university', 'high_school', 'secondary_school', 'primary_school', 'college_diploma', 'post_grad', 'madrassa']
house_elec [1, 0]
house_water_source ['water_impr', 'water_tank', 'water_unimpr', 'other']
water_in_compound ['yes', 'no', -1]
water_time [-1, 'min_low', 'min_mid', 'min_more']
water_clean ['w_good', 'w_idk', 'w_bad']
latrine_type ['lat_trad', 'lat_impr', 'lat_none']
no_latrine [-1, 'no_space', 'no_need', 'no_money']
share_latrine [0, 1]
tazkera_all [0, 1]
tazkera_hh_head [1, 0]
tazkera_project ['yes', 'idk', 'no']
tazkera_howto_project ['yes', 'no', 'idk']
f_tazkera [2, 0, -1, 1, 3, 5, 4, 9, 6, 7, 8, 11]
f_no_tazkera ['taz_needed', -1, 'taz_knowledge', 'taz_lengthy taz_origin', 'taz_needed taz_origin', 'taz_origin', 'taz_useful', 'taz_useful taz_needed', 'taz_useful taz_needed taz_origin', 'taz_lengthy', 'other', 'taz_needed taz_expensive', 'taz_needed taz_lengthy']
f_no_tazkera.not_useful [0, -1, 1]
f_no_tazkera.young [1, -1, 0]
f_no_tazkera.expensive [0, -1, 1]
f_no_tazkera.knowledge [0, -1, 1]
f_no_tazkera.lengthy [0, -1, 1]
f_no_tazkera.origin [0, -1, 1]
f_no_tazkera.other [0, -1, 1]
m_tazkera [3, 9, 7, 5, 1, -1, 2, 0, 4, 10, 6, 12, 8, 14]
m_no_tazkera [-1, 'taz_needed', 'taz_expensive', 'taz_lengthy taz_origin', 'taz_useful', 'taz_needed taz_origin', 'taz_origin', 'taz_useful taz_needed', 'taz_needed taz_lengthy', 'taz_needed taz_expensive', 'taz_lengthy', 'other']
m_no_tazkera.not_useful [-1, 0, 1]
m_no_tazkera.young [-1, 1, 0]
m_no_tazkera.expensive [-1, 0, 1]
m_no_tazkera.knowledge [-1, 0]
m_no_tazkera.lengthy [-1, 0, 1]
m_no_tazkera.origin [-1, 0, 1]
m_no_tazkera.other [-1, 0, 1]
time_health_facitility ['minh_more', 'minh_mid', 'minh_low', 'minh_no']

In [45]:
jlbd_services['tazkera_howto_project'].value_counts()

yes    398
no      35
idk     34
Name: tazkera_howto_project, dtype: int64

In [46]:
# dealing with a few specific cases
jlbd_services.loc[jlbd_services['water_in_compound'] == 'yes', 'water_in_compound'] = 1
jlbd_services.loc[jlbd_services['water_in_compound'] == 'no', 'water_in_compound'] = 0 

# We'll code the value idk (I don't know) with -2, and then binary encode the rest  
encode(jlbd_services, 'tazkera_project', 'idk', -2)    
encode(jlbd_services, 'tazkera_howto_project', 'idk', -2)    

jlbd_services.loc[jlbd_services['tazkera_project'] == 'yes', 'tazkera_project'] = 1
jlbd_services.loc[jlbd_services['tazkera_project'] == 'no', 'tazkera_project'] = 0

jlbd_services.loc[jlbd_services['tazkera_howto_project'] == 'yes', 'tazkera_howto_project'] = 1
jlbd_services.loc[jlbd_services['tazkera_howto_project'] == 'no', 'tazkera_howto_project'] = 0

display_df(jlbd_services)

f_12_lit_hh [2, 4, 1, 3, 0, 6, 5, 8, 10]
m_12_lit_hh [1, 6, 2, 4, 3, 0, 10, 7, 5, 8, 12]
f_illit ['no_need_read_write financial_issues', -1, 'family_restrictions financial_issues have_to_help_home', 'family_restrictions have_to_help_home', 'family_restrictions financial_issues', 'financial_issues', 'family_restrictions financial_issues school_too_far', 'financial_issues school_too_far', 'no_need_read_write financial_issues school_too_far', 'school_too_far', 'have_to_work_2_earn_money', 'family_restrictions', 'no_need_read_write', 'other', 'family_restrictions financial_issues school_too_far have_to_work_2_earn_money', 'financial_issues school_too_far have_to_help_home no_time', 'have_to_help_home', 'family_restrictions no_need_read_write', 'no_need_read_write financial_issues school_too_far language_problems', 'financial_issues have_to_help_home', 'no_need_read_write financial_issues have_to_help_home', 'financial_issues Tazkera_enrollment_problem have_to_help_home', 'family_restrictions no_need_read_write school_too_far have_to_help_home', 'family_restrictions no_need_read_write financial_issues have_to_help_home', 'family_restrictions no_need_read_write financial_issues', 'no_time', 'financial_issues have_to_work_2_earn_money', 'language_problems have_to_help_home', 'financial_issues school_too_far language_problems', 'no_need_read_write school_too_far language_problems', 'financial_issues no_time', 'family_restrictions school_too_far have_to_help_home', 'no_need_read_write financial_issues have_to_help_home no_time', 'family_restrictions no_time', 'no_need_read_write school_too_far', 'school_too_far language_problems', 'no_need_read_write financial_issues Tazkera_enrollment_problem', 'family_restrictions school_too_far', 'financial_issues language_problems have_to_help_home no_time', 'family_restrictions no_need_read_write have_to_help_home', 'financial_issues have_to_help_home no_time', 'Tazkera_enrollment_problem', 'family_restrictions no_need_read_write school_too_far', 'family_restrictions no_need_read_write have_to_help_home no_time']
f_illit.family [0, -1, 1]
f_illit.no_need [1, -1, 0]
f_illit.financial [1, -1, 0]
f_illit.school_far [0, -1, 1]
f_illit.language_pb [0, -1, 1]
f_illit.tazkera [0, -1, 1]
f_illit.make_money [0, -1, 1]
f_illit.help [0, -1, 1]
f_illit.time [0, -1, 1]
f_illit.other [0, -1, 1]
m_illit ['no_need_read_write have_to_work_2_earn_money', -1, 'family_restrictions financial_issues have_to_work_2_earn_money', 'financial_issues', 'financial_issues school_too_far', 'financial_issues school_too_far Tazkera_enrollment_problem', 'school_too_far', 'family_restrictions', 'financial_issues have_to_work_2_earn_money', 'no_need_read_write financial_issues', 'no_time', 'other', 'no_need_read_write financial_issues have_to_work_2_earn_money', 'financial_issues Tazkera_enrollment_problem have_to_work_2_earn_money no_time', 'family_restrictions no_need_read_write', 'financial_issues school_too_far language_problems', 'family_restrictions no_need_read_write school_too_far', 'no_need_read_write', 'financial_issues have_to_work_2_earn_money no_time', 'financial_issues Tazkera_enrollment_problem have_to_work_2_earn_money', 'have_to_work_2_earn_money', 'no_need_read_write school_too_far Tazkera_enrollment_problem', 'no_need_read_write financial_issues no_time', 'no_need_read_write financial_issues school_too_far', 'no_need_read_write school_too_far', 'financial_issues have_to_help_home', 'financial_issues Tazkera_enrollment_problem', 'school_too_far Tazkera_enrollment_problem', 'family_restrictions school_too_far', 'family_restrictions have_to_help_home', 'financial_issues other', 'no_need_read_write financial_issues language_problems', 'financial_issues school_too_far language_problems Tazkera_enrollment_problem', 'financial_issues language_problems Tazkera_enrollment_problem', 'no_need_read_write financial_issues have_to_work_2_earn_money no_time', 'family_restrictions financial_issues', 'financial_issues language_problems have_to_work_2_earn_money', 'school_too_far language_problems', 'financial_issues have_to_work_2_earn_money have_to_help_home no_time', 'no_need_read_write financial_issues have_to_help_home no_time']
m_illit.family [0, -1, 1]
m_illit.no_need [1, -1, 0]
m_illit.financial [0, -1, 1]
m_illit.school_far [0, -1, 1]
m_illit.language_pb [0, -1, 1]
m_illit.tazkera [0, -1, 1]
m_illit.make_money [1, -1, 0]
m_illit.help [0, -1, 1]
m_illit.time [0, -1, 1]
m_illit.other [0, -1, 1]
highest_edu ['no_scholing', 'university', 'high_school', 'secondary_school', 'primary_school', 'college_diploma', 'post_grad', 'madrassa']
house_elec [1, 0]
house_water_source ['water_impr', 'water_tank', 'water_unimpr', 'other']
water_in_compound [1, 0, -1]
water_time [-1, 'min_low', 'min_mid', 'min_more']
water_clean ['w_good', 'w_idk', 'w_bad']
latrine_type ['lat_trad', 'lat_impr', 'lat_none']
no_latrine [-1, 'no_space', 'no_need', 'no_money']
share_latrine [0, 1]
tazkera_all [0, 1]
tazkera_hh_head [1, 0]
tazkera_project [1, -2, 0]
tazkera_howto_project [1, 0, -2]
f_tazkera [2, 0, -1, 1, 3, 5, 4, 9, 6, 7, 8, 11]
f_no_tazkera ['taz_needed', -1, 'taz_knowledge', 'taz_lengthy taz_origin', 'taz_needed taz_origin', 'taz_origin', 'taz_useful', 'taz_useful taz_needed', 'taz_useful taz_needed taz_origin', 'taz_lengthy', 'other', 'taz_needed taz_expensive', 'taz_needed taz_lengthy']
f_no_tazkera.not_useful [0, -1, 1]
f_no_tazkera.young [1, -1, 0]
f_no_tazkera.expensive [0, -1, 1]
f_no_tazkera.knowledge [0, -1, 1]
f_no_tazkera.lengthy [0, -1, 1]
f_no_tazkera.origin [0, -1, 1]
f_no_tazkera.other [0, -1, 1]
m_tazkera [3, 9, 7, 5, 1, -1, 2, 0, 4, 10, 6, 12, 8, 14]
m_no_tazkera [-1, 'taz_needed', 'taz_expensive', 'taz_lengthy taz_origin', 'taz_useful', 'taz_needed taz_origin', 'taz_origin', 'taz_useful taz_needed', 'taz_needed taz_lengthy', 'taz_needed taz_expensive', 'taz_lengthy', 'other']
m_no_tazkera.not_useful [-1, 0, 1]
m_no_tazkera.young [-1, 1, 0]
m_no_tazkera.expensive [-1, 0, 1]
m_no_tazkera.knowledge [-1, 0]
m_no_tazkera.lengthy [-1, 0, 1]
m_no_tazkera.origin [-1, 0, 1]
m_no_tazkera.other [-1, 0, 1]
time_health_facitility ['minh_more', 'minh_mid', 'minh_low', 'minh_no']

#### 6. Assistance

In [47]:
jlbd_assistance = df.loc[:,"G01. Has your family ever received any assistance from any organisation or government, the local community or relatives?":
                           "g_social/g01assistance/g03/other"] 
#g_social/g01assistance/g03_other
jlbd_assistance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 14 columns):
G01. Has your family ever received any assistance from any organisation or government, the local community or relatives?    467 non-null object
g_social/g01assistance/g02                                                                                                  209 non-null object
g_social/g01assistance/g02/from_government                                                                                  209 non-null float64
g_social/g01assistance/g02/friend_or_relatives_personal_network                                                             209 non-null float64
g_social/g01assistance/g02/from_organization_NGO_or_UN_agency_both_local_or_international                                   209 non-null float64
g_social/g01assistance/g02/other                                                                                            209 non-null float64
g_social/g01assistance/g03                                                                                                  209 non-null object
Food Aid                                                                                                                    209 non-null float64
NFI (HH items, blankets, tarpaulin, clothes, hygiene items, etc)                                                            209 non-null float64
Health services                                                                                                             209 non-null float64
Housing assistance (rebuilt of shelter, etc)                                                                                209 non-null float64
Legal assistance (advise about rights, procetion, legal matters, etc)                                                       209 non-null float64
Assistance for a job                                                                                                        209 non-null float64
g_social/g01assistance/g03/other                                                                                            209 non-null float64
dtypes: float64(11), object(3)
memory usage: 51.2+ KB

In [48]:
jlbd_assistance = clean_df(jlbd_assistance, assistance_cols)

received_assist [1, 0]
assist_from ['from_organization_NGO_or_UN_agency_both_local_or_international', -1, 'from_government from_organization_NGO_or_UN_agency_both_local_or_international', 'friend_or_relatives_personal_network', 'from_government', 'friend_or_relatives_personal_network from_organization_NGO_or_UN_agency_both_local_or_international', 'from_government friend_or_relatives_personal_network']
assist_from.gvt [0, -1, 1]
assist_from.personal [0, -1, 1]
assist_from.ngo [1, -1, 0]
assist_from.other [0, -1]
assist_type ['assisstance_for_job', 'a_housing', -1, 'a_food a_health a_housing', 'a_health other', 'a_food', 'a_food assisstance_for_job', 'a_food a_health', 'a_health', 'a_nfi', 'a_health assisstance_for_job', 'a_food a_nfi', 'other', 'a_food a_health assisstance_for_job', 'a_nfi a_health', 'a_housing assisstance_for_job', 'a_food a_housing assisstance_for_job', 'a_housing other', 'assisstance_for_job other', 'a_health a_housing assisstance_for_job', 'a_nfi assisstance_for_job', 'a_legal', 'a_food a_housing']
assist_type.food [0, -1, 1]
assist_type.nfi [0, -1, 1]
assist_type.health [0, -1, 1]
assist_type.housing [0, 1, -1]
assist_type.legal [0, -1, 1]
assist_type.job [1, 0, -1]
assist_type.other [0, -1, 1]

#### 7.  Assets

In [49]:
jlbd_assets = df.loc[:,"H01. What is your present housing arrangement?":
                      "H18. Does the household have the necessary basic hygiene items?"]
jlbd_assets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 27 columns):
H01. What is your present housing arrangement?                     467 non-null object
H02. Do you own land?                                              467 non-null object
H03. Do you have a land deed for that land?                        249 non-null object
H04. Which livestock does your family own?                         467 non-null object
h_assets/h04/livestock_cattle                                      467 non-null bool
h_assets/h04/livestock_buffalo                                     467 non-null bool
h_assets/h04/livestock_horse                                       467 non-null bool
h_assets/h04/livestock_donkey                                      467 non-null bool
h_assets/h04/livestock_mule                                        467 non-null bool
h_assets/h04/livestock_poultry                                     467 non-null bool
h_assets/h04/livestock_goat                                        467 non-null bool
h_assets/h04/livestock_sheep                                       467 non-null bool
h_assets/h04/other                                                 467 non-null bool
H05. Fridge                                                        467 non-null object
H06. Stove/Oven/microwave                                          467 non-null object
H07. TV                                                            467 non-null object
H08. Radio                                                         467 non-null object
H09. VCR/DVD                                                       467 non-null object
H10. Mobile phone                                                  467 non-null object
H11. Computer/Tablet                                               467 non-null object
H12. Sewing machine/Embroidery machine                             467 non-null object
H13. Iron                                                          467 non-null object
H14. Bicycle                                                       467 non-null object
H15. Motorcycle                                                    467 non-null object
H16. Car/Zaranj                                                    467 non-null object
H17. Tractor/Other agricultural machinery                          467 non-null object
H18. Does the household have the necessary basic hygiene items?    467 non-null object
dtypes: bool(9), object(18)
memory usage: 69.9+ KB

In [50]:
# 4 cols missing compared to Herat: original_loc, present_loc, asset_no, livestock.other2
j_assets_cols = ['housing', 'own_land','land_deed','livestock','livestock.cattle','livestock.buffalo','livestock.horse',
                'livestock.donkey','livestock.mule','livestock.poultry','livestock.goat','livestock.sheep',
                'livestock.other','fridge','stove','tv','radio','dvd','mobile',
                'computer','sewing_mach','iron','bike','moto','car','tractor','basic_hygiene']

jlbd_assets = clean_df(jlbd_assets,j_assets_cols)

housing ['Other_own home_home_without_paying_rent)', 'rented_family_house_shered_with_others', 'Open spac_and_similar']
own_land ['no', 'Yes_my_orignal_location', 'Yes_my_present_location']
land_deed [-1, 'deed_formal', 'deed_no', 'deed_informal', 'deed_idk']
livestock ['None', 'livestock_buffalo', 'livestock_poultry', 'livestock_goat', 'livestock_buffalo livestock_poultry livestock_goat', 'livestock_mule', 'livestock_poultry livestock_goat', 'livestock_sheep', 'livestock_buffalo livestock_goat', 'livestock_buffalo livestock_poultry', 'livestock_poultry other']
livestock.cattle [False]
livestock.buffalo [0, 1]
livestock.horse [False]
livestock.donkey [False]
livestock.mule [0, 1]
livestock.poultry [0, 1]
livestock.goat [0, 1]
livestock.sheep [0, 1]
livestock.other [1, 0]
fridge [0, 1]
stove [0, 1]
tv [1, 0]
radio [0, 1]
dvd [0, 1]
mobile [1, 0]
computer [0, 1]
sewing_mach [0, 1]
iron [0, 1]
bike [0, 1]
moto [0, 1]
car [1, 0]
tractor [0, 1]
basic_hygiene [1, 0]

In [51]:
#We have 3 cols livestock.cattle, livestock.donkey, livestock.horse with all the same value, False.
#For compatibility with Herat_assets, we'll keep them, and just binary encode them
jlbd_assets.loc[jlbd_assets['livestock.cattle']==0, 
                ['livestock.cattle','livestock.donkey','livestock.horse']] = 0
display_df(jlbd_assets)

housing ['Other_own home_home_without_paying_rent)', 'rented_family_house_shered_with_others', 'Open spac_and_similar']
own_land ['no', 'Yes_my_orignal_location', 'Yes_my_present_location']
land_deed [-1, 'deed_formal', 'deed_no', 'deed_informal', 'deed_idk']
livestock ['None', 'livestock_buffalo', 'livestock_poultry', 'livestock_goat', 'livestock_buffalo livestock_poultry livestock_goat', 'livestock_mule', 'livestock_poultry livestock_goat', 'livestock_sheep', 'livestock_buffalo livestock_goat', 'livestock_buffalo livestock_poultry', 'livestock_poultry other']
livestock.cattle [0]
livestock.buffalo [0, 1]
livestock.horse [0]
livestock.donkey [0]
livestock.mule [0, 1]
livestock.poultry [0, 1]
livestock.goat [0, 1]
livestock.sheep [0, 1]
livestock.other [1, 0]
fridge [0, 1]
stove [0, 1]
tv [1, 0]
radio [0, 1]
dvd [0, 1]
mobile [1, 0]
computer [0, 1]
sewing_mach [0, 1]
iron [0, 1]
bike [0, 1]
moto [0, 1]
car [1, 0]
tractor [0, 1]
basic_hygiene [1, 0]

#### 8. Adaptive Capacity

In [52]:
jlbd_adaptive = df.loc[:,"Does any one in your familly earn income or bring money?":
                       "i_adaptive/i12/other"] 
jlbd_adaptive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 56 columns):
Does any one in your familly earn income or bring money?                                                   467 non-null object
I01. How many people are working in the family to earn money?                                              463 non-null float64
I01a. From what sources do they earn an income? (check all that applies/multiple choice)                   463 non-null object
i_adaptive/income_source/salaried_worker_private                                                           463 non-null float64
i_adaptive/income_source/salaried_worker_public                                                            463 non-null float64
i_adaptive/income_source/self_employed_own_business                                                        463 non-null float64
i_adaptive/income_source/employer                                                                          463 non-null float64
i_adaptive/income_source/day_laborer                                                                       463 non-null float64
i_adaptive/income_source/family_worker                                                                     463 non-null float64
i_adaptive/income_source/working_at_home                                                                   463 non-null float64
i_adaptive/income_source/apprentice                                                                        463 non-null float64
i_adaptive/income_source/other                                                                             463 non-null float64
I02.On average, how many days a week did they earn an income?                                              463 non-null float64
I02a. Did they bring home approx. the same amount of income every week/month?                              463 non-null object
I03. What is your average monthly income (entire HH, in AFA)?                                              467 non-null int64
I04.Has your income increased since joining the project?                                                   467 non-null object
I04a. if yes, how much it has increased? (in AFA, monthly average)                                         224 non-null float64
I04b. For VT benefciairies only - Are you currently working/active in the  {VT field they chose} field?    467 non-null object
I04c. if yes, in which form? (multiple choice )                                                            216 non-null object
i_adaptive/if_yes_which_form/Intern                                                                        216 non-null float64
i_adaptive/if_yes_which_form/Employee                                                                      216 non-null float64
i_adaptive/if_yes_which_form/Opened_owb_shop_outside_of_home                                               216 non-null float64
i_adaptive/if_yes_which_form/Opened_own_shop_at_home                                                       216 non-null float64
i_adaptive/if_yes_which_form/Opened_shop_with_other_people                                                 216 non-null float64
i_adaptive/if_yes_which_form/Employer                                                                      216 non-null float64
I05.Are all school-aged children (6-18)  attending school regularly?                                       467 non-null object
I06. How much of your family income is spent on food?                                                      467 non-null object
I07. How much of your family income is spent on fuel and heating?                                          467 non-null object
I08. How much does the family spend daily to go to work?                                                   467 non-null object
I09. How much is your family able to save per month?                                                       467 non-null object
I10. How much is your families present debt in total (excluding SHG loans)?                                467 non-null object
I11. Which of the following vulnerabilities apply to you or your family?                                   467 non-null object
i_adaptive/i11/vul_minor                                                                                   467 non-null bool
i_adaptive/i11/vul_woman                                                                                   467 non-null bool
i_adaptive/i11/vul_sing_male                                                                               467 non-null bool
i_adaptive/i11/vul_sing_female                                                                             467 non-null bool
i_adaptive/i11/vul_ill                                                                                     467 non-null bool
i_adaptive/i11/vul_poor                                                                                    467 non-null bool
i_adaptive/i11/vul_plw                                                                                     467 non-null bool
i_adaptive/i11/vul_drugs                                                                                   467 non-null bool
i_adaptive/i11/vul_old                                                                                     467 non-null bool
i_adaptive/i11/vul_pdisabled                                                                               467 non-null bool
i_adaptive/i11/vul_mdisabled                                                                               467 non-null bool
i_adaptive/i11/vul_medcial                                                                                 467 non-null bool
i_adaptive/i11/vul_special                                                                                 467 non-null bool
i_adaptive/i11/vul_ochildren                                                                               467 non-null bool
i_adaptive/i11/other                                                                                       467 non-null bool
i_adaptive/i11_other                                                                                       121 non-null object
I12. What would have helped you the most in the first six months of your displacement?                     101 non-null object
i_adaptive/i12/a_food                                                                                      101 non-null float64
i_adaptive/i12/a_nfi                                                                                       101 non-null float64
i_adaptive/i12/a_health                                                                                    101 non-null float64
i_adaptive/i12/a_housing                                                                                   101 non-null float64
i_adaptive/i12/a_legal                                                                                     101 non-null float64
i_adaptive/i12/assisstance_for_job                                                                         101 non-null float64
i_adaptive/i12/other                                                                                       101 non-null float64
dtypes: bool(15), float64(25), int64(1), object(15)
memory usage: 156.5+ KB

In [53]:
jlbd_adaptive = clean_df(jlbd_adaptive, adaptive_cols)

income_earner ['yes', 'no', 'No']
income_earner_hh [1, 3, 2, 5, 6, -1, 4, 5000, 7, 8]
income_source ['day_laborer', 'salaried_worker_public', 'salaried_worker_private', 'self_employed_own_business', 'working_at_home', 'family_worker', 'self_employed_own_business day_laborer', 'salaried_worker_public self_employed_own_business', 'day_laborer working_at_home', 'salaried_worker_private self_employed_own_business working_at_home', 'self_employed_own_business working_at_home', 'salaried_worker_private salaried_worker_public', 'salaried_worker_private working_at_home', 'salaried_worker_public day_laborer', -1, 'salaried_worker_private salaried_worker_public self_employed_own_business', 'employer', 'salaried_worker_public employer working_at_home', 'family_worker working_at_home', 'salaried_worker_private self_employed_own_business', 'salaried_worker_public employer', 'apprentice', 'self_employed_own_business family_worker', 'salaried_worker_public self_employed_own_business day_laborer']
income_source.salaried_private [0, 1, -1]
income_source.salaried_public [0, 1, -1]
income_source.self_employed [0, 1, -1]
income_source.employer [0, -1, 1]
income_source.day_laborer [1, 0, -1]
income_source.fam_worker [0, 1, -1]
income_source.home_work [0, 1, -1]
income_source.apprentice [0, -1, 1]
income_source.other [0, 1, -1]
income_days [3, 4, 6, 1, 7, 2, 5, -1]
income_var ['less_and_less', 'it_varies_every_week-month', 'same', 'dnk', 'more_and_more', -1, 'other']
avg_mth_income [5000, 6000, 12000, 7500, 400, 10000, 14000, 3000, 1000, 8000, 2000, 13000, 53000, 300, 18400, 4000, 20000, 15000, 11000, 7000, 9000, 25000, 13500, 60000, 17000, 16000, 0, 800, 200, 18000, 40000, 50000, 30000, 1200, 1600, 4500, 5500, 22000, 80000, 1300, 500, 1500, 2500]
income_incr_project ['yes', 'no', 'idk']
income_incr_project_amt [300, 200, 500, 400, 1000, -1, 2000, 4000, 100, 3, 600, 5000, 1500, 700, 900, 150, 3000, 7, 2500, 4, 250, 800, 6000, 13, 90000, 15]
vt_active ['no', 'yes', 'not_aplicable']
vt_form [-1, 'Intern', 'Opened_own_shop_at_home', 'Employee Opened_own_shop_at_home', 'Employee', 'Opened_shop_with_other_people', 'Opened_owb_shop_outside_of_home', 'Employee Opened_owb_shop_outside_of_home', 'Intern Employee', 'Employer']
vt_form.intern [-1, 1, 0]
vt_form.employee [-1, 0, 1]
vt_form.own_shop_outside [-1, 0, 1]
vt_form.own_shop_home [-1, 0, 1]
vt_form.shop_people [-1, 0, 1]
vt_form.employer [-1, 0, 1]
children_school [1, 0]
spending_food ['more_than_half', 'half_or_less', 'all_income']
spending_fuel ['half_or_less', 'more_than_half', 'all_income']
spending_transport ['transport_more', 'transport_less', 'transport_nothing']
saving ['saving_none', 'saving_less', 'saving_more']
debt ['debt_more', 'debt_mid', 'debt_less']
vul ['vul_ill', 'other', 'vul_minor vul_ill', 'vul_minor', 'vul_sing_male', 'vul_poor vul_old', 'vul_medcial', 'vul_ill vul_pdisabled', 'vul_minor vul_woman vul_ill', 'vul_poor other', 'vul_poor', 'vul_poor vul_drugs', 'vul_woman', 'vul_drugs', 'vul_minor vul_pdisabled', 'vul_ill vul_plw', 'vul_mdisabled', 'vul_minor vul_woman', 'vul_minor vul_woman vul_sing_male', 'vul_minor vul_woman vul_sing_female', 'vul_special', 'vul_pdisabled vul_mdisabled vul_medcial', 'vul_mdisabled vul_medcial other', 'vul_drugs vul_pdisabled vul_medcial other', 'vul_ill vul_drugs vul_pdisabled vul_medcial', 'vul_sing_female', 'vul_ochildren', 'vul_mdisabled vul_medcial', 'vul_sing_male vul_ill', 'vul_ill vul_mdisabled vul_medcial', 'vul_drugs vul_pdisabled vul_medcial', 'vul_minor vul_poor vul_drugs', 'vul_plw', 'vul_poor vul_pdisabled', 'vul_plw vul_special other', 'vul_ill vul_pdisabled vul_medcial', 'vul_ill vul_drugs vul_pdisabled vul_mdisabled vul_medcial', 'vul_ill vul_poor vul_pdisabled vul_mdisabled vul_medcial', 'vul_ill vul_pdisabled vul_mdisabled vul_medcial', 'vul_poor vul_medcial', 'vul_pdisabled', 'vul_minor vul_woman vul_drugs', 'vul_minor other', 'vul_poor vul_ochildren', 'vul_pdisabled vul_mdisabled', 'vul_drugs vul_pdisabled vul_mdisabled', 'vul_minor vul_special', 'vul_pdisabled other', 'vul_minor vul_medcial other', 'vul_pdisabled vul_medcial', 'vul_pdisabled vul_mdisabled other', 'vul_old vul_mdisabled', 'vul_drugs vul_pdisabled', 'vul_old', 'vul_sing_female vul_pdisabled', 'vul_sing_female vul_pdisabled vul_mdisabled', 'vul_minor vul_ill vul_poor', 'vul_minor vul_ill vul_pdisabled', 'vul_poor vul_plw', 'vul_poor vul_mdisabled', 'vul_ill vul_poor', 'vul_minor vul_poor']
vul.minor [0, 1]
vul.woman [0, 1]
vul.sing_male [0, 1]
vul.sing_female [0, 1]
vul.ill [1, 0]
vul.poor [0, 1]
vul.plw [0, 1]
vul.drugs [0, 1]
vul.old [0, 1]
vul.pdisabled [0, 1]
vul.mdisabled [0, 1]
vul_medical [0, 1]
vul.special [0, 1]
vul.ochildren [0, 1]
vul.other [0, 1]
vul.other2 [-1, 'No', 'دامنیت  خطر', 'امنیتی ستونزہ', 'Security problem', 'Security problems', 'امنیتی مشکلات', 'Security', 'ہو', 'Uامنیتی مشکلات', 'Living in poverty. Lack of means necessary to meet basic needs such as food, shelter & clothing. ', 'INo', 'Yes', 'Security condition.', 'Security situation. ', 'Security situation.', 'Security problems.', 'Security situation in Afg.', ' امنیتی مشکلات', 'Security problem.', 'Securitey', 'Seauritey', 'Security condition. ', 'Security situation in Afghanistan. ']
helpful_6mth [-1, 'a_food a_nfi a_health a_housing', 'a_food', 'a_health', 'a_food a_nfi a_health a_housing assisstance_for_job', 'a_food a_health a_housing', 'a_food a_nfi a_health', 'a_health a_housing', 'other', 'a_health a_housing assisstance_for_job', 'a_food a_nfi a_housing assisstance_for_job', 'a_food a_housing assisstance_for_job', 'a_food a_nfi assisstance_for_job', 'a_food a_nfi a_health assisstance_for_job', 'a_food a_nfi a_health a_legal assisstance_for_job other', 'a_food a_health a_housing assisstance_for_job', 'a_food a_health assisstance_for_job', 'a_health other', 'a_health assisstance_for_job', 'a_food a_health', 'a_food a_nfi', 'a_food assisstance_for_job', 'a_nfi assisstance_for_job', 'assisstance_for_job']
helpful_6mth.food [-1, 1, 0]
helpful_6mth.nfi [-1, 1, 0]
helpful_6mth.health [-1, 1, 0]
helpful_6mth.housing [-1, 1, 0]
helpful_6mth.legal [-1, 0, 1]
helpful_6mth.job_assist [-1, 0, 1]
helpful_6mth.other [-1, 0, 1]

In [54]:
# Dealing with a typo
jlbd_adaptive.loc[jlbd_adaptive['income_earner'] == 'No', 'income_earner'] = 0 
jlbd_adaptive.loc[jlbd_adaptive['income_earner'] == 'no', 'income_earner'] = 0 
jlbd_adaptive.loc[jlbd_adaptive['income_earner'] == 'yes', 'income_earner'] = 1

In [55]:
# Dealing with suspicious outlier
jlbd_adaptive['income_earner_hh'].value_counts()
#income_earner_hh relates to the number of people in the household that earn money. The outlier value of 5000 is not plausible. Let's take a closer look

 1       290
 2       124
 3        29
 4        10
 5         5
-1         4
 7         2
 5000      1
 8         1
 6         1
Name: income_earner_hh, dtype: int64

In [56]:
jlbd_adaptive.iloc[152,:]
#At least one member earning income given the context, 1 is the mode and the median, so we'll replace the outlier value by that
# np.median(jlbd_adaptive['income_earner_hh']) returns 1.0
jlbd_adaptive.loc[152,'income_earner_hh'] = 1

In [57]:
# Dealing with messy answers
jlbd_adaptive['vul.other2'].value_counts()

-1                                                                                                   346
No                                                                                                    47
Security problem                                                                                      28
Security                                                                                               6
Security situation.                                                                                    5
Security condition.                                                                                    5
Security condition.                                                                                    4
Security situation.                                                                                    4
امنیتی مشکلات                                                                                          3
Security problems.                                                                                     3
ہو                                                                                                     3
Seauritey                                                                                              1
Securitey                                                                                              1
Security problem.                                                                                      1
Uامنیتی مشکلات                                                                                         1
Security problems                                                                                      1
Security situation in Afg.                                                                             1
 امنیتی مشکلات                                                                                         1
امنیتی ستونزہ                                                                                          1
Security situation in Afghanistan.                                                                     1
INo                                                                                                    1
Living in poverty. Lack of means necessary to meet basic needs such as food, shelter & clothing.       1
Yes                                                                                                    1
دامنیت  خطر                                                                                            1
Name: vul.other2, dtype: int64

In [58]:
replacement_list = ['Security problem', 'Security', 'Security condition.', 'Security situation.', 
                   'Security condition. ','Security situation. ',  'Security problems.', 
                    'Security situation in Afghanistan.', 'Security situation in Afghanistan. ',
                   'Seauritey', 'Securitey', 'Security situation in Afg.', 'Security problems',
                   'Security problem.', 'امنیتی مشکلات', 'دامنیت  خطر', 'امنیتی مشکلات', 'امنیتی مشکلات',
                   'امنیتی ستونزہ', ' امنیتی مشکلات', 'Uامنیتی مشکلات']
jlbd_adaptive['vul.other2'] = jlbd_adaptive['vul.other2'].replace(replacement_list, 'security')
jlbd_adaptive.loc[jlbd_adaptive['vul.other2'] == 'No', 'vul.other2'] = 0
jlbd_adaptive.loc[jlbd_adaptive['vul.other2'] == 'INo', 'vul.other2'] = 0
jlbd_adaptive.loc[jlbd_adaptive['vul.other2'] == 'Yes', 'vul.other2'] = 1
jlbd_adaptive.loc[jlbd_adaptive['vul.other2'] == 'ہو', 'vul.other2'] = 1
jlbd_adaptive.loc[jlbd_adaptive['vul.other2'] == 
                  'Living in poverty. Lack of means necessary to meet basic needs such as food, shelter & clothing. ',
                  'vul.other2'] = 'poverty'

display_df(jlbd_adaptive)

income_earner [1, 0]
income_earner_hh [1, 3, 2, 5, 6, -1, 4, 7, 8]
income_source ['day_laborer', 'salaried_worker_public', 'salaried_worker_private', 'self_employed_own_business', 'working_at_home', 'family_worker', 'self_employed_own_business day_laborer', 'salaried_worker_public self_employed_own_business', 'day_laborer working_at_home', 'salaried_worker_private self_employed_own_business working_at_home', 'self_employed_own_business working_at_home', 'salaried_worker_private salaried_worker_public', 'salaried_worker_private working_at_home', 'salaried_worker_public day_laborer', -1, 'salaried_worker_private salaried_worker_public self_employed_own_business', 'employer', 'salaried_worker_public employer working_at_home', 'family_worker working_at_home', 'salaried_worker_private self_employed_own_business', 'salaried_worker_public employer', 'apprentice', 'self_employed_own_business family_worker', 'salaried_worker_public self_employed_own_business day_laborer']
income_source.salaried_private [0, 1, -1]
income_source.salaried_public [0, 1, -1]
income_source.self_employed [0, 1, -1]
income_source.employer [0, -1, 1]
income_source.day_laborer [1, 0, -1]
income_source.fam_worker [0, 1, -1]
income_source.home_work [0, 1, -1]
income_source.apprentice [0, -1, 1]
income_source.other [0, 1, -1]
income_days [3, 4, 6, 1, 7, 2, 5, -1]
income_var ['less_and_less', 'it_varies_every_week-month', 'same', 'dnk', 'more_and_more', -1, 'other']
avg_mth_income [5000, 6000, 12000, 7500, 400, 10000, 14000, 3000, 1000, 8000, 2000, 13000, 53000, 300, 18400, 4000, 20000, 15000, 11000, 7000, 9000, 25000, 13500, 60000, 17000, 16000, 0, 800, 200, 18000, 40000, 50000, 30000, 1200, 1600, 4500, 5500, 22000, 80000, 1300, 500, 1500, 2500]
income_incr_project ['yes', 'no', 'idk']
income_incr_project_amt [300, 200, 500, 400, 1000, -1, 2000, 4000, 100, 3, 600, 5000, 1500, 700, 900, 150, 3000, 7, 2500, 4, 250, 800, 6000, 13, 90000, 15]
vt_active ['no', 'yes', 'not_aplicable']
vt_form [-1, 'Intern', 'Opened_own_shop_at_home', 'Employee Opened_own_shop_at_home', 'Employee', 'Opened_shop_with_other_people', 'Opened_owb_shop_outside_of_home', 'Employee Opened_owb_shop_outside_of_home', 'Intern Employee', 'Employer']
vt_form.intern [-1, 1, 0]
vt_form.employee [-1, 0, 1]
vt_form.own_shop_outside [-1, 0, 1]
vt_form.own_shop_home [-1, 0, 1]
vt_form.shop_people [-1, 0, 1]
vt_form.employer [-1, 0, 1]
children_school [1, 0]
spending_food ['more_than_half', 'half_or_less', 'all_income']
spending_fuel ['half_or_less', 'more_than_half', 'all_income']
spending_transport ['transport_more', 'transport_less', 'transport_nothing']
saving ['saving_none', 'saving_less', 'saving_more']
debt ['debt_more', 'debt_mid', 'debt_less']
vul ['vul_ill', 'other', 'vul_minor vul_ill', 'vul_minor', 'vul_sing_male', 'vul_poor vul_old', 'vul_medcial', 'vul_ill vul_pdisabled', 'vul_minor vul_woman vul_ill', 'vul_poor other', 'vul_poor', 'vul_poor vul_drugs', 'vul_woman', 'vul_drugs', 'vul_minor vul_pdisabled', 'vul_ill vul_plw', 'vul_mdisabled', 'vul_minor vul_woman', 'vul_minor vul_woman vul_sing_male', 'vul_minor vul_woman vul_sing_female', 'vul_special', 'vul_pdisabled vul_mdisabled vul_medcial', 'vul_mdisabled vul_medcial other', 'vul_drugs vul_pdisabled vul_medcial other', 'vul_ill vul_drugs vul_pdisabled vul_medcial', 'vul_sing_female', 'vul_ochildren', 'vul_mdisabled vul_medcial', 'vul_sing_male vul_ill', 'vul_ill vul_mdisabled vul_medcial', 'vul_drugs vul_pdisabled vul_medcial', 'vul_minor vul_poor vul_drugs', 'vul_plw', 'vul_poor vul_pdisabled', 'vul_plw vul_special other', 'vul_ill vul_pdisabled vul_medcial', 'vul_ill vul_drugs vul_pdisabled vul_mdisabled vul_medcial', 'vul_ill vul_poor vul_pdisabled vul_mdisabled vul_medcial', 'vul_ill vul_pdisabled vul_mdisabled vul_medcial', 'vul_poor vul_medcial', 'vul_pdisabled', 'vul_minor vul_woman vul_drugs', 'vul_minor other', 'vul_poor vul_ochildren', 'vul_pdisabled vul_mdisabled', 'vul_drugs vul_pdisabled vul_mdisabled', 'vul_minor vul_special', 'vul_pdisabled other', 'vul_minor vul_medcial other', 'vul_pdisabled vul_medcial', 'vul_pdisabled vul_mdisabled other', 'vul_old vul_mdisabled', 'vul_drugs vul_pdisabled', 'vul_old', 'vul_sing_female vul_pdisabled', 'vul_sing_female vul_pdisabled vul_mdisabled', 'vul_minor vul_ill vul_poor', 'vul_minor vul_ill vul_pdisabled', 'vul_poor vul_plw', 'vul_poor vul_mdisabled', 'vul_ill vul_poor', 'vul_minor vul_poor']
vul.minor [0, 1]
vul.woman [0, 1]
vul.sing_male [0, 1]
vul.sing_female [0, 1]
vul.ill [1, 0]
vul.poor [0, 1]
vul.plw [0, 1]
vul.drugs [0, 1]
vul.old [0, 1]
vul.pdisabled [0, 1]
vul.mdisabled [0, 1]
vul_medical [0, 1]
vul.special [0, 1]
vul.ochildren [0, 1]
vul.other [0, 1]
vul.other2 [-1, 0, 'security', 1, 'poverty']
helpful_6mth [-1, 'a_food a_nfi a_health a_housing', 'a_food', 'a_health', 'a_food a_nfi a_health a_housing assisstance_for_job', 'a_food a_health a_housing', 'a_food a_nfi a_health', 'a_health a_housing', 'other', 'a_health a_housing assisstance_for_job', 'a_food a_nfi a_housing assisstance_for_job', 'a_food a_housing assisstance_for_job', 'a_food a_nfi assisstance_for_job', 'a_food a_nfi a_health assisstance_for_job', 'a_food a_nfi a_health a_legal assisstance_for_job other', 'a_food a_health a_housing assisstance_for_job', 'a_food a_health assisstance_for_job', 'a_health other', 'a_health assisstance_for_job', 'a_food a_health', 'a_food a_nfi', 'a_food assisstance_for_job', 'a_nfi assisstance_for_job', 'assisstance_for_job']
helpful_6mth.food [-1, 1, 0]
helpful_6mth.nfi [-1, 1, 0]
helpful_6mth.health [-1, 1, 0]
helpful_6mth.housing [-1, 1, 0]
helpful_6mth.legal [-1, 0, 1]
helpful_6mth.job_assist [-1, 0, 1]
helpful_6mth.other [-1, 0, 1]

#### 9. Jalalabad Final

In [59]:
jlbd_mid = pd.concat([jlbd_basics, jlbd_origin, jlbd_displacement, jlbd_food, 
                         jlbd_services, jlbd_assistance, jlbd_assets, jlbd_adaptive], 
                        axis = 1)
jlbd_mid.shape

(467, 252)

### Final midline

In [60]:
## Combining both df - we have a few columns we'll need to drop so that they match..
def missing_cols(list_df):
    # Return names of columns that are not in all dfs (works for more than 2 dfs) 
    col_dict = dict() #create a dict, key = col_name, value = count(col_name) in all dfs 
    for df in list_df:
        for col in df.columns:
            if col in col_dict:
                col_dict[col] +=1
            else:
                col_dict[col]=1
                
    # A feature is missing in at least 1 df if its dict value != len(list_df) 
    n = len(list_df)
    missing_cols = dict()
    for (key, value) in col_dict.items():
        if value != n:
            missing_cols[key] = value
    return missing_cols.keys()

missing_cols([herat_mid, jlbd_mid])

dict_keys(['original_loc', 'present_loc', 'asset_no', 'livestock.other2', 'no_latrine'])

In [61]:
herat_drop = ['original_loc', 'present_loc', 'asset_no', 'livestock.other2']
herat_combine = herat_mid.drop(herat_drop, axis=1)
jlbd_combine = jlbd_mid.drop('no_latrine', axis=1)

In [62]:
mid_final = pd.concat([herat_combine, jlbd_combine], axis=0)
mid_final.shape

(815, 251)

In [63]:
#Export all the data
mid_final.to_csv("cleaned_midline.csv",index=False)
herat_mid.to_csv("cleaned_midline_herat.csv",index=False)
jlbd_mid.to_csv("cleaned_midline_jlbd.csv",index=False)

### Conclusion

We now have clean data combining both Herat and Jalalabad surveys. 
The main tasks that were completed:
- Remove features with a high proportion of null values, or with a high proportion of identical values 
  as they won't be useful in analysis
- Simplify feature names
- Encode NA values (-1) and "I don't know" (-2)
- Binary encode categorical features 
- Convert relevant columns to integer type

Notes:
- I've coded some helper functions that could be reused for the other data.  
- All the categorical columns have been binary encoded. 
  However, I've kept the original columns to compare them easily with the other data. 
  But the data would be cleaner without. 
- Null values have been encoded with -1, 
  "I don't know" have been encoded with -2 (less frequent)

Next steps: 
- Perform exploratory data analysis on midline data
- Compare midterm data to baseline and endline